<?php

// This file is auto-generated by scripts/generate-client.php. Do not edit by hand.

declare(strict_types=1);

namespace Smartlyq\Resources;

use Smartlyq\CoreClient;

/** Account endpoints. */
class AccountResource
{
    public function __construct(private readonly CoreClient $client)
    {
    }

    /**
     * Get current user profile
     *
     * GET /me
     */
    public function getMe(array $options = []): array
    {
        return $this->client->request('GET', '/me', [
            'options' => $options,
        ]);
    }

    /**
     * Get usage summary
     *
     * GET /me/usage
     */
    public function getMeUsage(array $query = [], array $options = []): array
    {
        return $this->client->request('GET', '/me/usage', [
            'query' => $query,
            'options' => $options,
        ]);
    }

    /**
     * Get wallet balance
     *
     * GET /me/balance
     */
    public function getMeBalance(array $options = []): array
    {
        return $this->client->request('GET', '/me/balance', [
            'options' => $options,
        ]);
    }
}
