<?php

// This file is auto-generated by scripts/generate-client.php. Do not edit by hand.

declare(strict_types=1);

namespace Smartlyq\Resources;

use Smartlyq\CoreClient;

/** Ads endpoints. */
class AdsResource
{
    public function __construct(private readonly CoreClient $client)
    {
    }

    /**
     * List campaigns
     *
     * GET /ads/campaigns
     */
    public function listCampaigns(array $query = [], array $options = []): array
    {
        return $this->client->request('GET', '/ads/campaigns', [
            'query' => $query,
            'options' => $options,
        ]);
    }

    /**
     * Create a campaign
     *
     * POST /ads/campaigns
     */
    public function createCampaign(array $body, array $options = []): array
    {
        return $this->client->request('POST', '/ads/campaigns', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Get a campaign
     *
     * GET /ads/campaigns/{id}
     */
    public function getCampaign(string $id, array $options = []): array
    {
        return $this->client->request('GET', '/ads/campaigns/' . rawurlencode($id), [
            'options' => $options,
        ]);
    }

    /**
     * Update a campaign
     *
     * PATCH /ads/campaigns/{id}
     */
    public function updateCampaign(string $id, array $body, array $options = []): array
    {
        return $this->client->request('PATCH', '/ads/campaigns/' . rawurlencode($id), [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Delete a campaign
     *
     * DELETE /ads/campaigns/{id}
     */
    public function deleteCampaign(string $id, array $options = []): array
    {
        return $this->client->request('DELETE', '/ads/campaigns/' . rawurlencode($id), [
            'options' => $options,
        ]);
    }

    /**
     * Pause a campaign
     *
     * POST /ads/campaigns/{id}/pause
     */
    public function pauseCampaign(string $id, array $options = []): array
    {
        return $this->client->request('POST', '/ads/campaigns/' . rawurlencode($id) . '/pause', [
            'options' => $options,
        ]);
    }

    /**
     * Resume a campaign
     *
     * POST /ads/campaigns/{id}/resume
     */
    public function resumeCampaign(string $id, array $options = []): array
    {
        return $this->client->request('POST', '/ads/campaigns/' . rawurlencode($id) . '/resume', [
            'options' => $options,
        ]);
    }

    /**
     * Duplicate a campaign
     *
     * POST /ads/campaigns/{id}/duplicate
     */
    public function duplicateCampaign(string $id, array $options = []): array
    {
        return $this->client->request('POST', '/ads/campaigns/' . rawurlencode($id) . '/duplicate', [
            'options' => $options,
        ]);
    }

    /**
     * Archive a campaign
     *
     * POST /ads/campaigns/{id}/archive
     */
    public function archiveCampaign(string $id, array $options = []): array
    {
        return $this->client->request('POST', '/ads/campaigns/' . rawurlencode($id) . '/archive', [
            'options' => $options,
        ]);
    }

    /**
     * Bulk pause/resume campaigns
     *
     * POST /ads/campaigns/bulk-status
     */
    public function bulkCampaignStatus(array $body, array $options = []): array
    {
        return $this->client->request('POST', '/ads/campaigns/bulk-status', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * List ad sets
     *
     * GET /ads/ad-sets
     */
    public function listSets(array $query = [], array $options = []): array
    {
        return $this->client->request('GET', '/ads/ad-sets', [
            'query' => $query,
            'options' => $options,
        ]);
    }

    /**
     * Get an ad set
     *
     * GET /ads/ad-sets/{id}
     */
    public function getSet(string $id, array $options = []): array
    {
        return $this->client->request('GET', '/ads/ad-sets/' . rawurlencode($id), [
            'options' => $options,
        ]);
    }

    /**
     * Delete an ad set
     *
     * DELETE /ads/ad-sets/{id}
     */
    public function deleteSet(string $id, array $options = []): array
    {
        return $this->client->request('DELETE', '/ads/ad-sets/' . rawurlencode($id), [
            'options' => $options,
        ]);
    }

    /**
     * Pause an ad set
     *
     * POST /ads/ad-sets/{id}/pause
     */
    public function pauseSet(string $id, array $options = []): array
    {
        return $this->client->request('POST', '/ads/ad-sets/' . rawurlencode($id) . '/pause', [
            'options' => $options,
        ]);
    }

    /**
     * Resume an ad set
     *
     * POST /ads/ad-sets/{id}/resume
     */
    public function resumeSet(string $id, array $options = []): array
    {
        return $this->client->request('POST', '/ads/ad-sets/' . rawurlencode($id) . '/resume', [
            'options' => $options,
        ]);
    }

    /**
     * Duplicate an ad set
     *
     * POST /ads/ad-sets/{id}/duplicate
     */
    public function duplicateSet(string $id, array $options = []): array
    {
        return $this->client->request('POST', '/ads/ad-sets/' . rawurlencode($id) . '/duplicate', [
            'options' => $options,
        ]);
    }

    /**
     * Archive an ad set
     *
     * POST /ads/ad-sets/{id}/archive
     */
    public function archiveSet(string $id, array $options = []): array
    {
        return $this->client->request('POST', '/ads/ad-sets/' . rawurlencode($id) . '/archive', [
            'options' => $options,
        ]);
    }

    /**
     * List ads
     *
     * GET /ads/ads
     */
    public function list(array $query = [], array $options = []): array
    {
        return $this->client->request('GET', '/ads/ads', [
            'query' => $query,
            'options' => $options,
        ]);
    }

    /**
     * Get an ad
     *
     * GET /ads/ads/{id}
     */
    public function get(string $id, array $options = []): array
    {
        return $this->client->request('GET', '/ads/ads/' . rawurlencode($id), [
            'options' => $options,
        ]);
    }

    /**
     * Delete an ad
     *
     * DELETE /ads/ads/{id}
     */
    public function delete(string $id, array $options = []): array
    {
        return $this->client->request('DELETE', '/ads/ads/' . rawurlencode($id), [
            'options' => $options,
        ]);
    }

    /**
     * Pause an ad
     *
     * POST /ads/ads/{id}/pause
     */
    public function pause(string $id, array $options = []): array
    {
        return $this->client->request('POST', '/ads/ads/' . rawurlencode($id) . '/pause', [
            'options' => $options,
        ]);
    }

    /**
     * Resume an ad
     *
     * POST /ads/ads/{id}/resume
     */
    public function resume(string $id, array $options = []): array
    {
        return $this->client->request('POST', '/ads/ads/' . rawurlencode($id) . '/resume', [
            'options' => $options,
        ]);
    }

    /**
     * Duplicate an ad
     *
     * POST /ads/ads/{id}/duplicate
     */
    public function duplicate(string $id, array $options = []): array
    {
        return $this->client->request('POST', '/ads/ads/' . rawurlencode($id) . '/duplicate', [
            'options' => $options,
        ]);
    }

    /**
     * Archive an ad
     *
     * POST /ads/ads/{id}/archive
     */
    public function archive(string $id, array $options = []): array
    {
        return $this->client->request('POST', '/ads/ads/' . rawurlencode($id) . '/archive', [
            'options' => $options,
        ]);
    }

    /**
     * List audiences
     *
     * GET /ads/audiences
     */
    public function listAudiences(array $query = [], array $options = []): array
    {
        return $this->client->request('GET', '/ads/audiences', [
            'query' => $query,
            'options' => $options,
        ]);
    }

    /**
     * List pixels / conversion destinations
     *
     * GET /ads/pixels
     */
    public function listPixels(array $query = [], array $options = []): array
    {
        return $this->client->request('GET', '/ads/pixels', [
            'query' => $query,
            'options' => $options,
        ]);
    }

    /**
     * List lead forms
     *
     * GET /ads/lead-forms
     */
    public function listLeadForms(array $query = [], array $options = []): array
    {
        return $this->client->request('GET', '/ads/lead-forms', [
            'query' => $query,
            'options' => $options,
        ]);
    }

    /**
     * Create a lead form
     *
     * POST /ads/lead-forms
     */
    public function createLeadForm(array $body, array $options = []): array
    {
        return $this->client->request('POST', '/ads/lead-forms', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * List creatives
     *
     * GET /ads/creatives
     */
    public function listCreatives(array $query = [], array $options = []): array
    {
        return $this->client->request('GET', '/ads/creatives', [
            'query' => $query,
            'options' => $options,
        ]);
    }

    /**
     * Create a creative
     *
     * POST /ads/creatives
     */
    public function createCreative(array $body, array $options = []): array
    {
        return $this->client->request('POST', '/ads/creatives', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Update a creative
     *
     * PATCH /ads/creatives/{id}
     */
    public function updateCreative(string $id, array $body, array $options = []): array
    {
        return $this->client->request('PATCH', '/ads/creatives/' . rawurlencode($id), [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Delete a creative
     *
     * DELETE /ads/creatives/{id}
     */
    public function deleteCreative(string $id, array $options = []): array
    {
        return $this->client->request('DELETE', '/ads/creatives/' . rawurlencode($id), [
            'options' => $options,
        ]);
    }

    /**
     * List connected ad accounts
     *
     * GET /ads/accounts
     */
    public function listAccounts(array $options = []): array
    {
        return $this->client->request('GET', '/ads/accounts', [
            'options' => $options,
        ]);
    }

    /**
     * Account health and rate-limit diagnostics
     *
     * GET /ads/accounts/diagnostics
     */
    public function accountsDiagnostics(array $options = []): array
    {
        return $this->client->request('GET', '/ads/accounts/diagnostics', [
            'options' => $options,
        ]);
    }

    /**
     * List audit log entries
     *
     * GET /ads/audit-log
     */
    public function listAuditLog(array $query = [], array $options = []): array
    {
        return $this->client->request('GET', '/ads/audit-log', [
            'query' => $query,
            'options' => $options,
        ]);
    }

    /**
     * Audience-size estimate
     *
     * POST /ads/estimate
     */
    public function audienceEstimate(array $body, array $options = []): array
    {
        return $this->client->request('POST', '/ads/estimate', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Trigger an account sync
     *
     * POST /ads/sync
     */
    public function syncAccounts(array $options = []): array
    {
        return $this->client->request('POST', '/ads/sync', [
            'options' => $options,
        ]);
    }
}
