<?php

// This file is auto-generated by scripts/generate-client.php. Do not edit by hand.

declare(strict_types=1);

namespace Smartlyq\Resources;

use Smartlyq\CoreClient;

/** Analytics endpoints. */
class AnalyticsResource
{
    public function __construct(private readonly CoreClient $client)
    {
    }

    /**
     * Get analytics overview
     *
     * GET /analytics/overview
     */
    public function getOverview(array $query = [], array $options = []): array
    {
        return $this->client->request('GET', '/analytics/overview', [
            'query' => $query,
            'options' => $options,
        ]);
    }

    /**
     * Get post analytics
     *
     * GET /analytics/posts
     */
    public function getPosts(array $query = [], array $options = []): array
    {
        return $this->client->request('GET', '/analytics/posts', [
            'query' => $query,
            'options' => $options,
        ]);
    }

    /**
     * Get account analytics
     *
     * GET /analytics/accounts/{account_id}
     */
    public function getAccount(string $accountId, array $query = [], array $options = []): array
    {
        return $this->client->request('GET', '/analytics/accounts/' . rawurlencode($accountId), [
            'query' => $query,
            'options' => $options,
        ]);
    }

    /**
     * Daily metrics
     *
     * GET /analytics/daily-metrics
     */
    public function dailyMetrics(array $query = [], array $options = []): array
    {
        return $this->client->request('GET', '/analytics/daily-metrics', [
            'query' => $query,
            'options' => $options,
        ]);
    }

    /**
     * Best time to post
     *
     * GET /analytics/best-time
     */
    public function bestTime(array $query = [], array $options = []): array
    {
        return $this->client->request('GET', '/analytics/best-time', [
            'query' => $query,
            'options' => $options,
        ]);
    }

    /**
     * Content decay
     *
     * GET /analytics/content-decay
     */
    public function contentDecay(array $query = [], array $options = []): array
    {
        return $this->client->request('GET', '/analytics/content-decay', [
            'query' => $query,
            'options' => $options,
        ]);
    }

    /**
     * Posting frequency vs engagement
     *
     * GET /analytics/posting-frequency
     */
    public function postingFrequency(array $query = [], array $options = []): array
    {
        return $this->client->request('GET', '/analytics/posting-frequency', [
            'query' => $query,
            'options' => $options,
        ]);
    }

    /**
     * Post metric timeline
     *
     * GET /analytics/posts/{post_id}/timeline
     */
    public function postTimeline(string $postId, array $options = []): array
    {
        return $this->client->request('GET', '/analytics/posts/' . rawurlencode($postId) . '/timeline', [
            'options' => $options,
        ]);
    }
}
