<?php

// This file is auto-generated by scripts/generate-client.php. Do not edit by hand.

declare(strict_types=1);

namespace Smartlyq\Resources;

use Smartlyq\CoreClient;

/** Analytics endpoints. */
class AnalyticsResource
{
    public function __construct(private readonly CoreClient $client)
    {
    }

    /**
     * Get analytics overview
     *
     * GET /analytics/overview
     */
    public function getOverview(array $query = [], array $options = []): array
    {
        return $this->client->request('GET', '/analytics/overview', [
            'query' => $query,
            'options' => $options,
        ]);
    }

    /**
     * Get post analytics
     *
     * GET /analytics/posts
     */
    public function getPosts(array $query = [], array $options = []): array
    {
        return $this->client->request('GET', '/analytics/posts', [
            'query' => $query,
            'options' => $options,
        ]);
    }

    /**
     * Get account analytics
     *
     * GET /analytics/accounts/{account_id}
     */
    public function getAccount(string $accountId, array $query = [], array $options = []): array
    {
        return $this->client->request('GET', '/analytics/accounts/' . rawurlencode($accountId), [
            'query' => $query,
            'options' => $options,
        ]);
    }

    /**
     * Daily metrics
     *
     * GET /analytics/daily-metrics
     */
    public function dailyMetrics(array $query = [], array $options = []): array
    {
        return $this->client->request('GET', '/analytics/daily-metrics', [
            'query' => $query,
            'options' => $options,
        ]);
    }

    /**
     * Best time to post
     *
     * GET /analytics/best-time
     */
    public function bestTime(array $query = [], array $options = []): array
    {
        return $this->client->request('GET', '/analytics/best-time', [
            'query' => $query,
            'options' => $options,
        ]);
    }

    /**
     * Content decay
     *
     * GET /analytics/content-decay
     */
    public function contentDecay(array $query = [], array $options = []): array
    {
        return $this->client->request('GET', '/analytics/content-decay', [
            'query' => $query,
            'options' => $options,
        ]);
    }

    /**
     * Posting frequency vs engagement
     *
     * GET /analytics/posting-frequency
     */
    public function postingFrequency(array $query = [], array $options = []): array
    {
        return $this->client->request('GET', '/analytics/posting-frequency', [
            'query' => $query,
            'options' => $options,
        ]);
    }

    /**
     * Post metric timeline
     *
     * GET /analytics/posts/{post_id}/timeline
     */
    public function postTimeline(string $postId, array $options = []): array
    {
        return $this->client->request('GET', '/analytics/posts/' . rawurlencode($postId) . '/timeline', [
            'options' => $options,
        ]);
    }

    /**
     * Inbox volume
     *
     * GET /analytics/inbox/volume
     */
    public function inboxVolume(array $query = [], array $options = []): array
    {
        return $this->client->request('GET', '/analytics/inbox/volume', [
            'query' => $query,
            'options' => $options,
        ]);
    }

    /**
     * Inbox heatmap
     *
     * GET /analytics/inbox/heatmap
     */
    public function inboxHeatmap(array $query = [], array $options = []): array
    {
        return $this->client->request('GET', '/analytics/inbox/heatmap', [
            'query' => $query,
            'options' => $options,
        ]);
    }

    /**
     * Inbox source breakdown
     *
     * GET /analytics/inbox/source-breakdown
     */
    public function inboxSourceBreakdown(array $query = [], array $options = []): array
    {
        return $this->client->request('GET', '/analytics/inbox/source-breakdown', [
            'query' => $query,
            'options' => $options,
        ]);
    }

    /**
     * Inbox response time
     *
     * GET /analytics/inbox/response-time
     */
    public function inboxResponseTime(array $query = [], array $options = []): array
    {
        return $this->client->request('GET', '/analytics/inbox/response-time', [
            'query' => $query,
            'options' => $options,
        ]);
    }

    /**
     * Inbox top accounts
     *
     * GET /analytics/inbox/top-accounts
     */
    public function inboxTopAccounts(array $query = [], array $options = []): array
    {
        return $this->client->request('GET', '/analytics/inbox/top-accounts', [
            'query' => $query,
            'options' => $options,
        ]);
    }

    /**
     * Inbox conversation stats
     *
     * GET /analytics/inbox/conversations
     */
    public function inboxConversations(array $query = [], array $options = []): array
    {
        return $this->client->request('GET', '/analytics/inbox/conversations', [
            'query' => $query,
            'options' => $options,
        ]);
    }

    /**
     * Conversation analytics
     *
     * GET /analytics/inbox/conversations/{conversation_id}
     */
    public function inboxConversationDetail(string $conversationId, array $options = []): array
    {
        return $this->client->request('GET', '/analytics/inbox/conversations/' . rawurlencode($conversationId), [
            'options' => $options,
        ]);
    }

    /**
     * YouTube channel insights
     *
     * GET /analytics/youtube/channel-insights
     */
    public function getYoutubeChannelInsights(array $query = [], array $options = []): array
    {
        return $this->client->request('GET', '/analytics/youtube/channel-insights', [
            'query' => $query,
            'options' => $options,
        ]);
    }

    /**
     * YouTube daily views
     *
     * GET /analytics/youtube/daily-views
     */
    public function getYoutubeDailyViews(array $query = [], array $options = []): array
    {
        return $this->client->request('GET', '/analytics/youtube/daily-views', [
            'query' => $query,
            'options' => $options,
        ]);
    }

    /**
     * YouTube audience retention
     *
     * GET /analytics/youtube/video-retention
     */
    public function getYoutubeVideoRetention(array $query = [], array $options = []): array
    {
        return $this->client->request('GET', '/analytics/youtube/video-retention', [
            'query' => $query,
            'options' => $options,
        ]);
    }

    /**
     * YouTube viewer demographics
     *
     * GET /analytics/youtube/demographics
     */
    public function getYoutubeDemographics(array $query = [], array $options = []): array
    {
        return $this->client->request('GET', '/analytics/youtube/demographics', [
            'query' => $query,
            'options' => $options,
        ]);
    }
}
