<?php

// This file is auto-generated by scripts/generate-client.php. Do not edit by hand.

declare(strict_types=1);

namespace Smartlyq\Resources;

use Smartlyq\CoreClient;

/** Analytics endpoints. */
class AnalyticsResource
{
    public function __construct(private readonly CoreClient $client)
    {
    }

    /**
     * Get analytics overview
     *
     * GET /analytics/overview
     */
    public function getOverview(array $query = [], array $options = []): array
    {
        return $this->client->request('GET', '/analytics/overview', [
            'query' => $query,
            'options' => $options,
        ]);
    }

    /**
     * Get post analytics
     *
     * GET /analytics/posts
     */
    public function getPosts(array $query = [], array $options = []): array
    {
        return $this->client->request('GET', '/analytics/posts', [
            'query' => $query,
            'options' => $options,
        ]);
    }

    /**
     * Get account analytics
     *
     * GET /analytics/accounts/{account_id}
     */
    public function getAccount(string $accountId, array $query = [], array $options = []): array
    {
        return $this->client->request('GET', '/analytics/accounts/' . rawurlencode($accountId), [
            'query' => $query,
            'options' => $options,
        ]);
    }
}
