<?php

// This file is auto-generated by scripts/generate-client.php. Do not edit by hand.

declare(strict_types=1);

namespace Smartlyq\Resources;

use Smartlyq\CoreClient;

/** Articles endpoints. */
class ArticlesResource
{
    public function __construct(private readonly CoreClient $client)
    {
    }

    /**
     * Generate article
     *
     * POST /articles/generate
     */
    public function generate(array $body, array $options = []): array
    {
        return $this->client->request('POST', '/articles/generate', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * List articles
     *
     * GET /articles
     */
    public function list(array $query = [], array $options = []): array
    {
        return $this->client->request('GET', '/articles', [
            'query' => $query,
            'options' => $options,
        ]);
    }

    /**
     * Get article
     *
     * GET /articles/{article_id}
     */
    public function get(string $articleId, array $options = []): array
    {
        return $this->client->request('GET', '/articles/' . rawurlencode($articleId), [
            'options' => $options,
        ]);
    }

    /**
     * Delete article
     *
     * DELETE /articles/{article_id}
     */
    public function delete(string $articleId, array $options = []): array
    {
        return $this->client->request('DELETE', '/articles/' . rawurlencode($articleId), [
            'options' => $options,
        ]);
    }
}
