<?php

// This file is auto-generated by scripts/generate-client.php. Do not edit by hand.

declare(strict_types=1);

namespace Smartlyq\Resources;

use Smartlyq\CoreClient;

/** Audio endpoints. */
class AudioResource
{
    public function __construct(private readonly CoreClient $client)
    {
    }

    /**
     * Text to speech
     *
     * POST /audio/text-to-speech
     */
    public function textToSpeech(array $body, array $options = []): array
    {
        return $this->client->request('POST', '/audio/text-to-speech', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Speech to text
     *
     * POST /audio/speech-to-text
     */
    public function speechToText(array $body, array $options = []): array
    {
        return $this->client->request('POST', '/audio/speech-to-text', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Get audio
     *
     * GET /audio/{audio_id}
     */
    public function get(string $audioId, array $options = []): array
    {
        return $this->client->request('GET', '/audio/' . rawurlencode($audioId), [
            'options' => $options,
        ]);
    }
}
