<?php

// This file is auto-generated by scripts/generate-client.php. Do not edit by hand.

declare(strict_types=1);

namespace Smartlyq\Resources;

use Smartlyq\CoreClient;

/** Automations endpoints. */
class AutomationsResource
{
    public function __construct(private readonly CoreClient $client)
    {
    }

    /**
     * List automations
     *
     * GET /automations
     */
    public function list(array $query = [], array $options = []): array
    {
        return $this->client->request('GET', '/automations', [
            'query' => $query,
            'options' => $options,
        ]);
    }

    /**
     * Get automation
     *
     * GET /automations/{automation_id}
     */
    public function get(string $automationId, array $options = []): array
    {
        return $this->client->request('GET', '/automations/' . rawurlencode($automationId), [
            'options' => $options,
        ]);
    }

    /**
     * Activate automation
     *
     * POST /automations/{automation_id}/activate
     */
    public function activate(string $automationId, array $options = []): array
    {
        return $this->client->request('POST', '/automations/' . rawurlencode($automationId) . '/activate', [
            'options' => $options,
        ]);
    }

    /**
     * Pause automation
     *
     * POST /automations/{automation_id}/deactivate
     */
    public function deactivate(string $automationId, array $options = []): array
    {
        return $this->client->request('POST', '/automations/' . rawurlencode($automationId) . '/deactivate', [
            'options' => $options,
        ]);
    }

    /**
     * Trigger automation
     *
     * POST /automations/{automation_id}/trigger
     */
    public function trigger(string $automationId, array $body = [], array $options = []): array
    {
        return $this->client->request('POST', '/automations/' . rawurlencode($automationId) . '/trigger', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * List runs
     *
     * GET /automations/{automation_id}/runs
     */
    public function listRuns(string $automationId, array $query = [], array $options = []): array
    {
        return $this->client->request('GET', '/automations/' . rawurlencode($automationId) . '/runs', [
            'query' => $query,
            'options' => $options,
        ]);
    }

    /**
     * Get run
     *
     * GET /automations/{automation_id}/runs/{run_id}
     */
    public function getRun(string $automationId, string $runId, array $options = []): array
    {
        return $this->client->request('GET', '/automations/' . rawurlencode($automationId) . '/runs/' . rawurlencode($runId), [
            'options' => $options,
        ]);
    }
}
