<?php

// This file is auto-generated by scripts/generate-client.php. Do not edit by hand.

declare(strict_types=1);

namespace Smartlyq\Resources;

use Smartlyq\CoreClient;

/** Calendar endpoints. */
class CalendarResource
{
    public function __construct(private readonly CoreClient $client)
    {
    }

    /**
     * List booking pages
     *
     * GET /calendar/event-types
     */
    public function listEventTypes(array $options = []): array
    {
        return $this->client->request('GET', '/calendar/event-types', [
            'options' => $options,
        ]);
    }

    /**
     * List open slots
     *
     * GET /calendar/slots
     */
    public function listSlots(array $query = [], array $options = []): array
    {
        return $this->client->request('GET', '/calendar/slots', [
            'query' => $query,
            'options' => $options,
        ]);
    }

    /**
     * Take a booking
     *
     * POST /calendar/bookings
     */
    public function createBooking(array $body, array $options = []): array
    {
        return $this->client->request('POST', '/calendar/bookings', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Cancel a booking
     *
     * POST /calendar/bookings/{id}/cancel
     */
    public function cancelBooking(string $id, array $body = [], array $options = []): array
    {
        return $this->client->request('POST', '/calendar/bookings/' . rawurlencode($id) . '/cancel', [
            'body' => $body,
            'options' => $options,
        ]);
    }
}
