<?php

// This file is auto-generated by scripts/generate-client.php. Do not edit by hand.

declare(strict_types=1);

namespace Smartlyq\Resources;

use Smartlyq\CoreClient;

/** AI Captain endpoints. */
class CaptainResource
{
    public function __construct(private readonly CoreClient $client)
    {
    }

    /**
     * Send AI Captain message
     *
     * POST /captain/messages
     */
    public function sendMessage(array $body, array $options = []): array
    {
        return $this->client->request('POST', '/captain/messages', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * List AI Captain conversations
     *
     * GET /captain/conversations
     */
    public function listConversations(array $query = [], array $options = []): array
    {
        return $this->client->request('GET', '/captain/conversations', [
            'query' => $query,
            'options' => $options,
        ]);
    }

    /**
     * Get AI Captain conversation
     *
     * GET /captain/conversations/{conversation_id}
     */
    public function getConversation(string $conversationId, array $options = []): array
    {
        return $this->client->request('GET', '/captain/conversations/' . rawurlencode($conversationId), [
            'options' => $options,
        ]);
    }
}
