<?php

// This file is auto-generated by scripts/generate-client.php. Do not edit by hand.

declare(strict_types=1);

namespace Smartlyq\Resources;

use Smartlyq\CoreClient;

/** Chatbot endpoints. */
class ChatbotsResource
{
    public function __construct(private readonly CoreClient $client)
    {
    }

    /**
     * List chatbots
     *
     * GET /chatbots
     */
    public function list(array $query = [], array $options = []): array
    {
        return $this->client->request('GET', '/chatbots', [
            'query' => $query,
            'options' => $options,
        ]);
    }

    /**
     * Create chatbot
     *
     * POST /chatbots
     */
    public function create(array $body, array $options = []): array
    {
        return $this->client->request('POST', '/chatbots', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Get chatbot
     *
     * GET /chatbots/{id}
     */
    public function get(string $id, array $options = []): array
    {
        return $this->client->request('GET', '/chatbots/' . rawurlencode($id), [
            'options' => $options,
        ]);
    }

    /**
     * Update chatbot
     *
     * PATCH /chatbots/{id}
     */
    public function update(string $id, array $body, array $options = []): array
    {
        return $this->client->request('PATCH', '/chatbots/' . rawurlencode($id), [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Delete chatbot
     *
     * DELETE /chatbots/{id}
     */
    public function delete(string $id, array $options = []): array
    {
        return $this->client->request('DELETE', '/chatbots/' . rawurlencode($id), [
            'options' => $options,
        ]);
    }

    /**
     * Start chatbot training
     *
     * POST /chatbots/{id}/train
     */
    public function train(string $id, array $options = []): array
    {
        return $this->client->request('POST', '/chatbots/' . rawurlencode($id) . '/train', [
            'options' => $options,
        ]);
    }

    /**
     * Get chatbot training status
     *
     * GET /chatbots/{id}/train-status
     */
    public function getTrainStatus(string $id, array $options = []): array
    {
        return $this->client->request('GET', '/chatbots/' . rawurlencode($id) . '/train-status', [
            'options' => $options,
        ]);
    }

    /**
     * Send chatbot message
     *
     * POST /chatbots/{id}/messages
     */
    public function sendMessage(string $id, array $body, array $options = []): array
    {
        return $this->client->request('POST', '/chatbots/' . rawurlencode($id) . '/messages', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * List chatbot conversations
     *
     * GET /chatbots/{id}/conversations
     */
    public function listConversations(string $id, array $query = [], array $options = []): array
    {
        return $this->client->request('GET', '/chatbots/' . rawurlencode($id) . '/conversations', [
            'query' => $query,
            'options' => $options,
        ]);
    }

    /**
     * Get conversation messages
     *
     * GET /chatbots/{id}/conversations/{conv_id}/messages
     */
    public function getConversationMessages(string $id, string $convId, array $options = []): array
    {
        return $this->client->request('GET', '/chatbots/' . rawurlencode($id) . '/conversations/' . rawurlencode($convId) . '/messages', [
            'options' => $options,
        ]);
    }
}
