<?php

// This file is auto-generated by scripts/generate-client.php. Do not edit by hand.

declare(strict_types=1);

namespace Smartlyq\Resources;

use Smartlyq\CoreClient;

/** Comments endpoints. */
class CommentsResource
{
    public function __construct(private readonly CoreClient $client)
    {
    }

    /**
     * List comments
     *
     * GET /social/comments
     */
    public function list(array $query = [], array $options = []): array
    {
        return $this->client->request('GET', '/social/comments', [
            'query' => $query,
            'options' => $options,
        ]);
    }

    /**
     * Reply to a comment
     *
     * POST /social/comments/{comment_id}/reply
     */
    public function replyTo(string $commentId, array $body, array $options = []): array
    {
        return $this->client->request('POST', '/social/comments/' . rawurlencode($commentId) . '/reply', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Hide or unhide a comment
     *
     * POST /social/comments/{comment_id}/hide
     */
    public function hide(string $commentId, array $options = []): array
    {
        return $this->client->request('POST', '/social/comments/' . rawurlencode($commentId) . '/hide', [
            'options' => $options,
        ]);
    }

    /**
     * Delete a comment
     *
     * DELETE /social/comments/{comment_id}
     */
    public function delete(string $commentId, array $options = []): array
    {
        return $this->client->request('DELETE', '/social/comments/' . rawurlencode($commentId), [
            'options' => $options,
        ]);
    }

    /**
     * Get one post's comments (threaded)
     *
     * GET /social/comments/{post_id}
     */
    public function getPost(string $postId, array $options = []): array
    {
        return $this->client->request('GET', '/social/comments/' . rawurlencode($postId), [
            'options' => $options,
        ]);
    }
}
