<?php

// This file is auto-generated by scripts/generate-client.php. Do not edit by hand.

declare(strict_types=1);

namespace Smartlyq\Resources;

use Smartlyq\CoreClient;

/** CRM Contacts endpoints. */
class ContactsResource
{
    public function __construct(private readonly CoreClient $client)
    {
    }

    /**
     * List contacts
     *
     * GET /contacts
     */
    public function list(array $query = [], array $options = []): array
    {
        return $this->client->request('GET', '/contacts', [
            'query' => $query,
            'options' => $options,
        ]);
    }

    /**
     * Create or upsert a contact
     *
     * POST /contacts
     */
    public function create(array $body, array $options = []): array
    {
        return $this->client->request('POST', '/contacts', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Get a contact
     *
     * GET /contacts/{id}
     */
    public function get(string $id, array $options = []): array
    {
        return $this->client->request('GET', '/contacts/' . rawurlencode($id), [
            'options' => $options,
        ]);
    }

    /**
     * Update a contact
     *
     * PATCH /contacts/{id}
     */
    public function update(string $id, array $body, array $options = []): array
    {
        return $this->client->request('PATCH', '/contacts/' . rawurlencode($id), [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Add tags to a contact
     *
     * POST /contacts/{id}/tags
     */
    public function addTags(string $id, array $body, array $options = []): array
    {
        return $this->client->request('POST', '/contacts/' . rawurlencode($id) . '/tags', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Remove tags from a contact
     *
     * DELETE /contacts/{id}/tags
     */
    public function removeTags(string $id, array $body, array $options = []): array
    {
        return $this->client->request('DELETE', '/contacts/' . rawurlencode($id) . '/tags', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * List contact notes
     *
     * GET /contacts/{id}/notes
     */
    public function listNotes(string $id, array $options = []): array
    {
        return $this->client->request('GET', '/contacts/' . rawurlencode($id) . '/notes', [
            'options' => $options,
        ]);
    }

    /**
     * Add a note to a contact
     *
     * POST /contacts/{id}/notes
     */
    public function addNote(string $id, array $body, array $options = []): array
    {
        return $this->client->request('POST', '/contacts/' . rawurlencode($id) . '/notes', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Enroll a contact in an automation
     *
     * POST /contacts/{id}/enroll
     */
    public function enroll(string $id, array $body, array $options = []): array
    {
        return $this->client->request('POST', '/contacts/' . rawurlencode($id) . '/enroll', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Log a message on a contact's timeline
     *
     * POST /contacts/{id}/messages
     */
    public function addMessage(string $id, array $body, array $options = []): array
    {
        return $this->client->request('POST', '/contacts/' . rawurlencode($id) . '/messages', [
            'body' => $body,
            'options' => $options,
        ]);
    }
}
