<?php

// This file is auto-generated by scripts/generate-client.php. Do not edit by hand.

declare(strict_types=1);

namespace Smartlyq\Resources;

use Smartlyq\CoreClient;

/** Content endpoints. */
class ContentResource
{
    public function __construct(private readonly CoreClient $client)
    {
    }

    /**
     * Rewrite content
     *
     * POST /content/rewrite
     */
    public function rewrite(array $body, array $options = []): array
    {
        return $this->client->request('POST', '/content/rewrite', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Generate a social caption
     *
     * POST /content/caption
     */
    public function generateCaption(array $body = [], array $options = []): array
    {
        return $this->client->request('POST', '/content/caption', [
            'body' => $body,
            'options' => $options,
        ]);
    }
}
