<?php

// This file is auto-generated by scripts/generate-client.php. Do not edit by hand.

declare(strict_types=1);

namespace Smartlyq\Resources;

use Smartlyq\CoreClient;

/** CRM Companies endpoints. */
class CRMCompaniesResource
{
    public function __construct(private readonly CoreClient $client)
    {
    }

    /**
     * List companies
     *
     * GET /companies
     */
    public function list(array $query = [], array $options = []): array
    {
        return $this->client->request('GET', '/companies', [
            'query' => $query,
            'options' => $options,
        ]);
    }

    /**
     * Create a company
     *
     * POST /companies
     */
    public function create(array $body, array $options = []): array
    {
        return $this->client->request('POST', '/companies', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Get a company
     *
     * GET /companies/{id}
     */
    public function get(string $id, array $options = []): array
    {
        return $this->client->request('GET', '/companies/' . rawurlencode($id), [
            'options' => $options,
        ]);
    }

    /**
     * Update a company
     *
     * PATCH /companies/{id}
     */
    public function update(string $id, array $body, array $options = []): array
    {
        return $this->client->request('PATCH', '/companies/' . rawurlencode($id), [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Delete a company
     *
     * DELETE /companies/{id}
     */
    public function delete(string $id, array $options = []): array
    {
        return $this->client->request('DELETE', '/companies/' . rawurlencode($id), [
            'options' => $options,
        ]);
    }

    /**
     * Link a contact to a company
     *
     * POST /companies/{id}/contacts
     */
    public function linkContact(string $id, array $body, array $options = []): array
    {
        return $this->client->request('POST', '/companies/' . rawurlencode($id) . '/contacts', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Unlink a contact from a company
     *
     * DELETE /companies/{id}/contacts
     */
    public function unlinkContact(string $id, array $body, array $options = []): array
    {
        return $this->client->request('DELETE', '/companies/' . rawurlencode($id) . '/contacts', [
            'body' => $body,
            'options' => $options,
        ]);
    }
}
