<?php

// This file is auto-generated by scripts/generate-client.php. Do not edit by hand.

declare(strict_types=1);

namespace Smartlyq\Resources;

use Smartlyq\CoreClient;

/** CRM endpoints. */
class CRMResource
{
    public function __construct(private readonly CoreClient $client)
    {
    }

    /**
     * Delete contact
     *
     * DELETE /contacts/{id}
     */
    public function deleteContact(string $id, array $options = []): array
    {
        return $this->client->request('DELETE', '/contacts/' . rawurlencode($id), [
            'options' => $options,
        ]);
    }

    /**
     * Bulk import contacts
     *
     * POST /contacts/bulk
     */
    public function bulkImportContacts(array $body, array $options = []): array
    {
        return $this->client->request('POST', '/contacts/bulk', [
            'body' => $body,
            'options' => $options,
        ]);
    }
}
