<?php

// This file is auto-generated by scripts/generate-client.php. Do not edit by hand.

declare(strict_types=1);

namespace Smartlyq\Resources;

use Smartlyq\CoreClient;

/** CRM Tags endpoints. */
class CRMTagsResource
{
    public function __construct(private readonly CoreClient $client)
    {
    }

    /**
     * List tags
     *
     * GET /tags
     */
    public function list(array $options = []): array
    {
        return $this->client->request('GET', '/tags', [
            'options' => $options,
        ]);
    }

    /**
     * Create a tag
     *
     * POST /tags
     */
    public function create(array $body, array $options = []): array
    {
        return $this->client->request('POST', '/tags', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Rename a tag
     *
     * POST /tags/rename
     */
    public function rename(array $body, array $options = []): array
    {
        return $this->client->request('POST', '/tags/rename', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Merge tags
     *
     * POST /tags/merge
     */
    public function merge(array $body, array $options = []): array
    {
        return $this->client->request('POST', '/tags/merge', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Delete a tag
     *
     * POST /tags/delete
     */
    public function delete(array $body, array $options = []): array
    {
        return $this->client->request('POST', '/tags/delete', [
            'body' => $body,
            'options' => $options,
        ]);
    }
}
