<?php

// This file is auto-generated by scripts/generate-client.php. Do not edit by hand.

declare(strict_types=1);

namespace Smartlyq\Resources;

use Smartlyq\CoreClient;

/** CRM Tasks endpoints. */
class CRMTasksResource
{
    public function __construct(private readonly CoreClient $client)
    {
    }

    /**
     * List tasks
     *
     * GET /tasks
     */
    public function list(array $query = [], array $options = []): array
    {
        return $this->client->request('GET', '/tasks', [
            'query' => $query,
            'options' => $options,
        ]);
    }

    /**
     * Create a task
     *
     * POST /tasks
     */
    public function create(array $body, array $options = []): array
    {
        return $this->client->request('POST', '/tasks', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Get a task
     *
     * GET /tasks/{id}
     */
    public function get(string $id, array $options = []): array
    {
        return $this->client->request('GET', '/tasks/' . rawurlencode($id), [
            'options' => $options,
        ]);
    }

    /**
     * Update a task
     *
     * PATCH /tasks/{id}
     */
    public function update(string $id, array $body, array $options = []): array
    {
        return $this->client->request('PATCH', '/tasks/' . rawurlencode($id), [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Delete a task
     *
     * DELETE /tasks/{id}
     */
    public function delete(string $id, array $options = []): array
    {
        return $this->client->request('DELETE', '/tasks/' . rawurlencode($id), [
            'options' => $options,
        ]);
    }

    /**
     * Log time on a task
     *
     * POST /tasks/{id}/time
     */
    public function logTime(string $id, array $body, array $options = []): array
    {
        return $this->client->request('POST', '/tasks/' . rawurlencode($id) . '/time', [
            'body' => $body,
            'options' => $options,
        ]);
    }
}
