<?php

// This file is auto-generated by scripts/generate-client.php. Do not edit by hand.

declare(strict_types=1);

namespace Smartlyq\Resources;

use Smartlyq\CoreClient;

/** CRM Custom Fields endpoints. */
class CustomFieldsResource
{
    public function __construct(private readonly CoreClient $client)
    {
    }

    /**
     * List custom fields
     *
     * GET /custom-fields
     */
    public function list(array $options = []): array
    {
        return $this->client->request('GET', '/custom-fields', [
            'options' => $options,
        ]);
    }

    /**
     * Create a custom field
     *
     * POST /custom-fields
     */
    public function create(array $body, array $options = []): array
    {
        return $this->client->request('POST', '/custom-fields', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Delete a custom field
     *
     * DELETE /custom-fields/{id}
     */
    public function delete(string $id, array $options = []): array
    {
        return $this->client->request('DELETE', '/custom-fields/' . rawurlencode($id), [
            'options' => $options,
        ]);
    }
}
