<?php

// This file is auto-generated by scripts/generate-client.php. Do not edit by hand.

declare(strict_types=1);

namespace Smartlyq\Resources;

use Smartlyq\CoreClient;

/** Edits endpoints. */
class EditsResource
{
    public function __construct(private readonly CoreClient $client)
    {
    }

    /**
     * List video edits
     *
     * GET /edits
     */
    public function list(array $query = [], array $options = []): array
    {
        return $this->client->request('GET', '/edits', [
            'query' => $query,
            'options' => $options,
        ]);
    }

    /**
     * Create a video edit
     *
     * POST /edits
     */
    public function create(array $body, array $options = []): array
    {
        return $this->client->request('POST', '/edits', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * List edit options
     *
     * GET /edits/options
     */
    public function listOptions(array $options = []): array
    {
        return $this->client->request('GET', '/edits/options', [
            'options' => $options,
        ]);
    }

    /**
     * Get a video edit
     *
     * GET /edits/{uid}
     */
    public function get(string $uid, array $options = []): array
    {
        return $this->client->request('GET', '/edits/' . rawurlencode($uid), [
            'options' => $options,
        ]);
    }

    /**
     * Update a video edit
     *
     * PATCH /edits/{uid}
     */
    public function update(string $uid, array $body, array $options = []): array
    {
        return $this->client->request('PATCH', '/edits/' . rawurlencode($uid), [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Export a video edit
     *
     * POST /edits/{uid}/export
     */
    public function export(string $uid, array $options = []): array
    {
        return $this->client->request('POST', '/edits/' . rawurlencode($uid) . '/export', [
            'options' => $options,
        ]);
    }
}
