<?php

// This file is auto-generated by scripts/generate-client.php. Do not edit by hand.

declare(strict_types=1);

namespace Smartlyq\Resources;

use Smartlyq\CoreClient;

/** Images endpoints. */
class ImagesResource
{
    public function __construct(private readonly CoreClient $client)
    {
    }

    /**
     * Generate image
     *
     * POST /images/generate
     */
    public function generate(array $body, array $options = []): array
    {
        return $this->client->request('POST', '/images/generate', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * List images
     *
     * GET /images
     */
    public function list(array $query = [], array $options = []): array
    {
        return $this->client->request('GET', '/images', [
            'query' => $query,
            'options' => $options,
        ]);
    }

    /**
     * Get image
     *
     * GET /images/{image_id}
     */
    public function get(string $imageId, array $options = []): array
    {
        return $this->client->request('GET', '/images/' . rawurlencode($imageId), [
            'options' => $options,
        ]);
    }

    /**
     * Delete image
     *
     * DELETE /images/{image_id}
     */
    public function delete(string $imageId, array $options = []): array
    {
        return $this->client->request('DELETE', '/images/' . rawurlencode($imageId), [
            'options' => $options,
        ]);
    }
}
