<?php

// This file is auto-generated by scripts/generate-client.php. Do not edit by hand.

declare(strict_types=1);

namespace Smartlyq\Resources;

use Smartlyq\CoreClient;

/** Jobs endpoints. */
class JobsResource
{
    public function __construct(private readonly CoreClient $client)
    {
    }

    /**
     * List jobs
     *
     * GET /jobs
     */
    public function list(array $query = [], array $options = []): array
    {
        return $this->client->request('GET', '/jobs', [
            'query' => $query,
            'options' => $options,
        ]);
    }

    /**
     * Get job
     *
     * GET /jobs/{job_id}
     */
    public function get(string $jobId, array $options = []): array
    {
        return $this->client->request('GET', '/jobs/' . rawurlencode($jobId), [
            'options' => $options,
        ]);
    }

    /**
     * Cancel job
     *
     * POST /jobs/{job_id}/cancel
     */
    public function cancel(string $jobId, array $body = [], array $options = []): array
    {
        return $this->client->request('POST', '/jobs/' . rawurlencode($jobId) . '/cancel', [
            'body' => $body,
            'options' => $options,
        ]);
    }
}
