<?php

// This file is auto-generated by scripts/generate-client.php. Do not edit by hand.

declare(strict_types=1);

namespace Smartlyq\Resources;

use Smartlyq\CoreClient;

/** Logs endpoints. */
class LogsResource
{
    public function __construct(private readonly CoreClient $client)
    {
    }

    /**
     * List developer logs
     *
     * GET /logs
     */
    public function list(array $query = [], array $options = []): array
    {
        return $this->client->request('GET', '/logs', [
            'query' => $query,
            'options' => $options,
        ]);
    }
}
