<?php

// This file is auto-generated by scripts/generate-client.php. Do not edit by hand.

declare(strict_types=1);

namespace Smartlyq\Resources;

use Smartlyq\CoreClient;

/** Media endpoints. */
class MediaResource
{
    public function __construct(private readonly CoreClient $client)
    {
    }

    /**
     * List media
     *
     * GET /media
     */
    public function list(array $query = [], array $options = []): array
    {
        return $this->client->request('GET', '/media', [
            'query' => $query,
            'options' => $options,
        ]);
    }

    /**
     * Get media
     *
     * GET /media/{media_id}
     */
    public function get(string $mediaId, array $options = []): array
    {
        return $this->client->request('GET', '/media/' . rawurlencode($mediaId), [
            'options' => $options,
        ]);
    }

    /**
     * Delete media
     *
     * DELETE /media/{media_id}
     */
    public function delete(string $mediaId, array $options = []): array
    {
        return $this->client->request('DELETE', '/media/' . rawurlencode($mediaId), [
            'options' => $options,
        ]);
    }

    /**
     * Get presigned upload URL
     *
     * POST /media/upload-url
     */
    public function getUploadUrl(array $body, array $options = []): array
    {
        return $this->client->request('POST', '/media/upload-url', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Upload a file directly
     *
     * POST /media/upload-direct
     */
    public function uploadDirect(array $body, array $options = []): array
    {
        return $this->client->request('POST', '/media/upload-direct', [
            'body' => $body,
            'options' => $options,
        ]);
    }
}
