<?php

// This file is auto-generated by scripts/generate-client.php. Do not edit by hand.

declare(strict_types=1);

namespace Smartlyq\Resources;

use Smartlyq\CoreClient;

/** Direct Messages endpoints. */
class MessagesResource
{
    public function __construct(private readonly CoreClient $client)
    {
    }

    /**
     * List DM conversations
     *
     * GET /social/conversations
     */
    public function listConversations(array $query = [], array $options = []): array
    {
        return $this->client->request('GET', '/social/conversations', [
            'query' => $query,
            'options' => $options,
        ]);
    }

    /**
     * List messages in a conversation
     *
     * GET /social/conversations/{conversation_id}/messages
     */
    public function list(string $conversationId, array $query = [], array $options = []): array
    {
        return $this->client->request('GET', '/social/conversations/' . rawurlencode($conversationId) . '/messages', [
            'query' => $query,
            'options' => $options,
        ]);
    }

    /**
     * Send a direct message
     *
     * POST /social/conversations/{conversation_id}/messages
     */
    public function send(string $conversationId, array $body, array $options = []): array
    {
        return $this->client->request('POST', '/social/conversations/' . rawurlencode($conversationId) . '/messages', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Mark a conversation read
     *
     * POST /social/conversations/{conversation_id}/read
     */
    public function markConversationRead(string $conversationId, array $options = []): array
    {
        return $this->client->request('POST', '/social/conversations/' . rawurlencode($conversationId) . '/read', [
            'options' => $options,
        ]);
    }
}
