<?php

// This file is auto-generated by scripts/generate-client.php. Do not edit by hand.

declare(strict_types=1);

namespace Smartlyq\Resources;

use Smartlyq\CoreClient;

/** CRM Opportunities endpoints. */
class OpportunitiesResource
{
    public function __construct(private readonly CoreClient $client)
    {
    }

    /**
     * List pipelines
     *
     * GET /pipelines
     */
    public function listPipelines(array $options = []): array
    {
        return $this->client->request('GET', '/pipelines', [
            'options' => $options,
        ]);
    }

    /**
     * Create a pipeline
     *
     * POST /pipelines
     */
    public function createPipeline(array $body, array $options = []): array
    {
        return $this->client->request('POST', '/pipelines', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * List opportunities
     *
     * GET /opportunities
     */
    public function list(array $query = [], array $options = []): array
    {
        return $this->client->request('GET', '/opportunities', [
            'query' => $query,
            'options' => $options,
        ]);
    }

    /**
     * Create an opportunity
     *
     * POST /opportunities
     */
    public function create(array $body, array $options = []): array
    {
        return $this->client->request('POST', '/opportunities', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Get an opportunity
     *
     * GET /opportunities/{id}
     */
    public function get(string $id, array $options = []): array
    {
        return $this->client->request('GET', '/opportunities/' . rawurlencode($id), [
            'options' => $options,
        ]);
    }

    /**
     * Update an opportunity
     *
     * PATCH /opportunities/{id}
     */
    public function update(string $id, array $body, array $options = []): array
    {
        return $this->client->request('PATCH', '/opportunities/' . rawurlencode($id), [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Delete an opportunity
     *
     * DELETE /opportunities/{id}
     */
    public function delete(string $id, array $options = []): array
    {
        return $this->client->request('DELETE', '/opportunities/' . rawurlencode($id), [
            'options' => $options,
        ]);
    }

    /**
     * Update opportunity status
     *
     * POST /opportunities/{id}/status
     */
    public function updateStatus(string $id, array $body, array $options = []): array
    {
        return $this->client->request('POST', '/opportunities/' . rawurlencode($id) . '/status', [
            'body' => $body,
            'options' => $options,
        ]);
    }
}
