<?php

// This file is auto-generated by scripts/generate-client.php. Do not edit by hand.

declare(strict_types=1);

namespace Smartlyq\Resources;

use Smartlyq\CoreClient;

/** Presentations endpoints. */
class PresentationsResource
{
    public function __construct(private readonly CoreClient $client)
    {
    }

    /**
     * Generate presentation
     *
     * POST /presentations/generate
     */
    public function generate(array $body, array $options = []): array
    {
        return $this->client->request('POST', '/presentations/generate', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * List presentations
     *
     * GET /presentations
     */
    public function list(array $query = [], array $options = []): array
    {
        return $this->client->request('GET', '/presentations', [
            'query' => $query,
            'options' => $options,
        ]);
    }

    /**
     * Get presentation
     *
     * GET /presentations/{presentation_id}
     */
    public function get(string $presentationId, array $options = []): array
    {
        return $this->client->request('GET', '/presentations/' . rawurlencode($presentationId), [
            'options' => $options,
        ]);
    }

    /**
     * Delete presentation
     *
     * DELETE /presentations/{presentation_id}
     */
    public function delete(string $presentationId, array $options = []): array
    {
        return $this->client->request('DELETE', '/presentations/' . rawurlencode($presentationId), [
            'options' => $options,
        ]);
    }
}
