<?php

// This file is auto-generated by scripts/generate-client.php. Do not edit by hand.

declare(strict_types=1);

namespace Smartlyq\Resources;

use Smartlyq\CoreClient;

/** Profiles endpoints. */
class ProfilesResource
{
    public function __construct(private readonly CoreClient $client)
    {
    }

    /**
     * List profiles
     *
     * GET /profiles
     */
    public function list(array $query = [], array $options = []): array
    {
        return $this->client->request('GET', '/profiles', [
            'query' => $query,
            'options' => $options,
        ]);
    }

    /**
     * Create a profile
     *
     * POST /profiles
     */
    public function create(array $body, array $options = []): array
    {
        return $this->client->request('POST', '/profiles', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Get a profile
     *
     * GET /profiles/{id}
     */
    public function get(string $id, array $options = []): array
    {
        return $this->client->request('GET', '/profiles/' . rawurlencode($id), [
            'options' => $options,
        ]);
    }

    /**
     * Delete a profile
     *
     * DELETE /profiles/{id}
     */
    public function delete(string $id, array $body, array $options = []): array
    {
        return $this->client->request('DELETE', '/profiles/' . rawurlencode($id), [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * List a profile's connected accounts
     *
     * GET /profiles/{id}/accounts
     */
    public function listAccounts(string $id, array $options = []): array
    {
        return $this->client->request('GET', '/profiles/' . rawurlencode($id) . '/accounts', [
            'options' => $options,
        ]);
    }

    /**
     * Pause a profile
     *
     * POST /profiles/{id}/pause
     */
    public function pause(string $id, array $options = []): array
    {
        return $this->client->request('POST', '/profiles/' . rawurlencode($id) . '/pause', [
            'options' => $options,
        ]);
    }

    /**
     * Resume a profile
     *
     * POST /profiles/{id}/resume
     */
    public function resume(string $id, array $options = []): array
    {
        return $this->client->request('POST', '/profiles/' . rawurlencode($id) . '/resume', [
            'options' => $options,
        ]);
    }

    /**
     * Create a hosted connect link
     *
     * POST /profiles/{id}/connect-link
     */
    public function createConnectLink(string $id, array $body = [], array $options = []): array
    {
        return $this->client->request('POST', '/profiles/' . rawurlencode($id) . '/connect-link', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Get a raw connect URL for one platform
     *
     * POST /profiles/{id}/connect/{platform}
     */
    public function createConnectUrl(string $id, string $platform, array $body = [], array $options = []): array
    {
        return $this->client->request('POST', '/profiles/' . rawurlencode($id) . '/connect/' . rawurlencode($platform), [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Account billing summary
     *
     * GET /me/account-billing
     */
    public function getAccountBilling(array $options = []): array
    {
        return $this->client->request('GET', '/me/account-billing', [
            'options' => $options,
        ]);
    }
}
