<?php

// This file is auto-generated by scripts/generate-client.php. Do not edit by hand.

declare(strict_types=1);

namespace Smartlyq\Resources;

use Smartlyq\CoreClient;

/** Reviews endpoints. */
class ReviewsResource
{
    public function __construct(private readonly CoreClient $client)
    {
    }

    /**
     * List reviews
     *
     * GET /reviews
     */
    public function list(array $query = [], array $options = []): array
    {
        return $this->client->request('GET', '/reviews', [
            'query' => $query,
            'options' => $options,
        ]);
    }

    /**
     * Reply to review
     *
     * POST /reviews/{review_id}/reply
     */
    public function replyTo(string $reviewId, array $body, array $options = []): array
    {
        return $this->client->request('POST', '/reviews/' . rawurlencode($reviewId) . '/reply', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Sync reviews
     *
     * POST /reviews/sync
     */
    public function sync(array $body = [], array $options = []): array
    {
        return $this->client->request('POST', '/reviews/sync', [
            'body' => $body,
            'options' => $options,
        ]);
    }
}
