<?php

// This file is auto-generated by scripts/generate-client.php. Do not edit by hand.

declare(strict_types=1);

namespace Smartlyq\Resources;

use Smartlyq\CoreClient;

/** SEO endpoints. */
class SeoResource
{
    public function __construct(private readonly CoreClient $client)
    {
    }

    /**
     * Keyword research
     *
     * POST /seo/keyword-research
     */
    public function keywordResearch(array $body, array $options = []): array
    {
        return $this->client->request('POST', '/seo/keyword-research', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Live SERP lookup
     *
     * POST /seo/serp
     */
    public function serp(array $body, array $options = []): array
    {
        return $this->client->request('POST', '/seo/serp', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Keyword difficulty
     *
     * POST /seo/keyword-difficulty
     */
    public function keywordDifficulty(array $body, array $options = []): array
    {
        return $this->client->request('POST', '/seo/keyword-difficulty', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Ranked keywords (rank tracking)
     *
     * POST /seo/ranked-keywords
     */
    public function rankedKeywords(array $body, array $options = []): array
    {
        return $this->client->request('POST', '/seo/ranked-keywords', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Domain rank overview
     *
     * POST /seo/domain-overview
     */
    public function domainOverview(array $body, array $options = []): array
    {
        return $this->client->request('POST', '/seo/domain-overview', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Organic competitors
     *
     * POST /seo/competitors
     */
    public function competitors(array $body, array $options = []): array
    {
        return $this->client->request('POST', '/seo/competitors', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Backlink profile summary
     *
     * POST /seo/backlinks-summary
     */
    public function backlinksSummary(array $body, array $options = []): array
    {
        return $this->client->request('POST', '/seo/backlinks-summary', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * On-page SEO audit
     *
     * POST /seo/audit
     */
    public function audit(array $body, array $options = []): array
    {
        return $this->client->request('POST', '/seo/audit', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Backlink prospects (link gap)
     *
     * POST /seo/backlink-prospects
     */
    public function backlinkProspects(array $body, array $options = []): array
    {
        return $this->client->request('POST', '/seo/backlink-prospects', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Referring domains
     *
     * POST /seo/referring-domains
     */
    public function referringDomains(array $body, array $options = []): array
    {
        return $this->client->request('POST', '/seo/referring-domains', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Backlink anchors
     *
     * POST /seo/backlink-anchors
     */
    public function backlinkAnchors(array $body, array $options = []): array
    {
        return $this->client->request('POST', '/seo/backlink-anchors', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Backlink spam score
     *
     * POST /seo/spam-score
     */
    public function spamScore(array $body, array $options = []): array
    {
        return $this->client->request('POST', '/seo/spam-score', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Historical rank overview
     *
     * POST /seo/rank-history
     */
    public function rankHistory(array $body, array $options = []): array
    {
        return $this->client->request('POST', '/seo/rank-history', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Deep site audit
     *
     * POST /seo/site-audit
     */
    public function siteAudit(array $body, array $options = []): array
    {
        return $this->client->request('POST', '/seo/site-audit', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * AI Visibility: brand lookup
     *
     * POST /seo/brand-lookup
     */
    public function brandLookup(array $body, array $options = []): array
    {
        return $this->client->request('POST', '/seo/brand-lookup', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * AI Visibility: prompt explorer
     *
     * POST /seo/prompt-explorer
     */
    public function promptExplorer(array $body, array $options = []): array
    {
        return $this->client->request('POST', '/seo/prompt-explorer', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * AI Visibility Audit (async)
     *
     * POST /seo/ai-audit
     */
    public function aiAudit(array $body, array $options = []): array
    {
        return $this->client->request('POST', '/seo/ai-audit', [
            'body' => $body,
            'options' => $options,
        ]);
    }
}
