<?php

// This file is auto-generated by scripts/generate-client.php. Do not edit by hand.

declare(strict_types=1);

namespace Smartlyq\Resources;

use Smartlyq\CoreClient;

/** Shorts endpoints. */
class ShortsResource
{
    public function __construct(private readonly CoreClient $client)
    {
    }

    /**
     * Generate viral shorts from a long video
     *
     * POST /shorts/generate
     */
    public function generate(array $body = [], array $options = []): array
    {
        return $this->client->request('POST', '/shorts/generate', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * List shorts jobs
     *
     * GET /shorts
     */
    public function list(array $query = [], array $options = []): array
    {
        return $this->client->request('GET', '/shorts', [
            'query' => $query,
            'options' => $options,
        ]);
    }

    /**
     * Get shorts job + clips
     *
     * GET /shorts/{uid}
     */
    public function get(string $uid, array $options = []): array
    {
        return $this->client->request('GET', '/shorts/' . rawurlencode($uid), [
            'options' => $options,
        ]);
    }
}
