<?php

// This file is auto-generated by scripts/generate-client.php. Do not edit by hand.

declare(strict_types=1);

namespace Smartlyq\Resources;

use Smartlyq\CoreClient;

/** Social endpoints. */
class SocialResource
{
    public function __construct(private readonly CoreClient $client)
    {
    }

    /**
     * List social accounts
     *
     * GET /social/accounts
     */
    public function listAccounts(array $options = []): array
    {
        return $this->client->request('GET', '/social/accounts', [
            'options' => $options,
        ]);
    }

    /**
     * List social posts
     *
     * GET /social/posts
     */
    public function listPosts(array $query = [], array $options = []): array
    {
        return $this->client->request('GET', '/social/posts', [
            'query' => $query,
            'options' => $options,
        ]);
    }

    /**
     * Create post (publish immediately)
     *
     * POST /social/posts
     */
    public function createPost(array $body, array $options = []): array
    {
        return $this->client->request('POST', '/social/posts', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Schedule post
     *
     * POST /social/posts/schedule
     */
    public function schedulePost(array $body, array $options = []): array
    {
        return $this->client->request('POST', '/social/posts/schedule', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Get social post
     *
     * GET /social/posts/{post_id}
     */
    public function getPost(string $postId, array $options = []): array
    {
        return $this->client->request('GET', '/social/posts/' . rawurlencode($postId), [
            'options' => $options,
        ]);
    }

    /**
     * Update social post
     *
     * PATCH /social/posts/{post_id}
     */
    public function updatePost(string $postId, array $body, array $options = []): array
    {
        return $this->client->request('PATCH', '/social/posts/' . rawurlencode($postId), [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Delete social post
     *
     * DELETE /social/posts/{post_id}
     */
    public function deletePost(string $postId, array $options = []): array
    {
        return $this->client->request('DELETE', '/social/posts/' . rawurlencode($postId), [
            'options' => $options,
        ]);
    }

    /**
     * Rename account
     *
     * PATCH /social/accounts/{account_id}
     */
    public function updateAccount(string $accountId, array $body, array $options = []): array
    {
        return $this->client->request('PATCH', '/social/accounts/' . rawurlencode($accountId), [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Disconnect a social account
     *
     * DELETE /social/accounts/{account_id}
     */
    public function disconnectAccount(string $accountId, array $options = []): array
    {
        return $this->client->request('DELETE', '/social/accounts/' . rawurlencode($accountId), [
            'options' => $options,
        ]);
    }

    /**
     * Account health
     *
     * GET /social/accounts/{account_id}/health
     */
    public function getAccountHealth(string $accountId, array $options = []): array
    {
        return $this->client->request('GET', '/social/accounts/' . rawurlencode($accountId) . '/health', [
            'options' => $options,
        ]);
    }

    /**
     * Account reconnect URL
     *
     * GET /social/accounts/{account_id}/reconnect-url
     */
    public function getAccountReconnectUrl(string $accountId, array $options = []): array
    {
        return $this->client->request('GET', '/social/accounts/' . rawurlencode($accountId) . '/reconnect-url', [
            'options' => $options,
        ]);
    }

    /**
     * Pause posting to an account
     *
     * POST /social/accounts/{account_id}/pause
     */
    public function pauseAccount(string $accountId, array $options = []): array
    {
        return $this->client->request('POST', '/social/accounts/' . rawurlencode($accountId) . '/pause', [
            'options' => $options,
        ]);
    }

    /**
     * Resume posting to an account
     *
     * POST /social/accounts/{account_id}/resume
     */
    public function resumeAccount(string $accountId, array $options = []): array
    {
        return $this->client->request('POST', '/social/accounts/' . rawurlencode($accountId) . '/resume', [
            'options' => $options,
        ]);
    }

    /**
     * Retry publishing a post
     *
     * POST /social/posts/{post_id}/retry
     */
    public function retryPost(string $postId, array $body, array $options = []): array
    {
        return $this->client->request('POST', '/social/posts/' . rawurlencode($postId) . '/retry', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Poll headless connection status
     *
     * GET /social/connect/{platform}
     */
    public function connectAccountStatus(string $platform, array $options = []): array
    {
        return $this->client->request('GET', '/social/connect/' . rawurlencode($platform), [
            'options' => $options,
        ]);
    }

    /**
     * Start headless account connection
     *
     * POST /social/connect/{platform}
     */
    public function connectAccount(string $platform, array $body = [], array $options = []): array
    {
        return $this->client->request('POST', '/social/connect/' . rawurlencode($platform), [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * List queues
     *
     * GET /social/queues
     */
    public function listQueues(array $options = []): array
    {
        return $this->client->request('GET', '/social/queues', [
            'options' => $options,
        ]);
    }

    /**
     * Create queue
     *
     * POST /social/queues
     */
    public function createQueue(array $body, array $options = []): array
    {
        return $this->client->request('POST', '/social/queues', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Get queue
     *
     * GET /social/queues/{queue_id}
     */
    public function getQueue(string $queueId, array $options = []): array
    {
        return $this->client->request('GET', '/social/queues/' . rawurlencode($queueId), [
            'options' => $options,
        ]);
    }

    /**
     * Update queue
     *
     * PUT /social/queues/{queue_id}
     */
    public function updateQueue(string $queueId, array $body, array $options = []): array
    {
        return $this->client->request('PUT', '/social/queues/' . rawurlencode($queueId), [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Delete queue
     *
     * DELETE /social/queues/{queue_id}
     */
    public function deleteQueue(string $queueId, array $options = []): array
    {
        return $this->client->request('DELETE', '/social/queues/' . rawurlencode($queueId), [
            'options' => $options,
        ]);
    }

    /**
     * Get next open slot
     *
     * GET /social/queues/{queue_id}/next-slot
     */
    public function getQueueNextSlot(string $queueId, array $options = []): array
    {
        return $this->client->request('GET', '/social/queues/' . rawurlencode($queueId) . '/next-slot', [
            'options' => $options,
        ]);
    }

    /**
     * Preview upcoming slots
     *
     * GET /social/queues/{queue_id}/preview
     */
    public function previewQueueSlots(string $queueId, array $query = [], array $options = []): array
    {
        return $this->client->request('GET', '/social/queues/' . rawurlencode($queueId) . '/preview', [
            'query' => $query,
            'options' => $options,
        ]);
    }

    /**
     * Unpublish post
     *
     * POST /social/posts/{post_id}/unpublish
     */
    public function unpublishPost(string $postId, array $body = [], array $options = []): array
    {
        return $this->client->request('POST', '/social/posts/' . rawurlencode($postId) . '/unpublish', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Validate post content
     *
     * POST /social/validate/post
     */
    public function validatePost(array $body, array $options = []): array
    {
        return $this->client->request('POST', '/social/validate/post', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Validate media URL
     *
     * POST /social/validate/media
     */
    public function validateMedia(array $body, array $options = []): array
    {
        return $this->client->request('POST', '/social/validate/media', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Stop recycling
     *
     * DELETE /social/posts/{post_id}/recycle
     */
    public function stopPostRecycle(string $postId, array $options = []): array
    {
        return $this->client->request('DELETE', '/social/posts/' . rawurlencode($postId) . '/recycle', [
            'options' => $options,
        ]);
    }

    /**
     * Bulk schedule posts
     *
     * POST /social/posts/bulk
     */
    public function bulkSchedulePosts(array $body, array $options = []): array
    {
        return $this->client->request('POST', '/social/posts/bulk', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Validate a bulk batch
     *
     * POST /social/posts/bulk/validate
     */
    public function validateBulkBatch(array $body, array $options = []): array
    {
        return $this->client->request('POST', '/social/posts/bulk/validate', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Bulk account health
     *
     * GET /social/accounts/health
     */
    public function bulkAccountHealth(array $options = []): array
    {
        return $this->client->request('GET', '/social/accounts/health', [
            'options' => $options,
        ]);
    }

    /**
     * Follower stats
     *
     * GET /social/accounts/follower-stats
     */
    public function accountFollowerStats(array $query = [], array $options = []): array
    {
        return $this->client->request('GET', '/social/accounts/follower-stats', [
            'query' => $query,
            'options' => $options,
        ]);
    }

    /**
     * TikTok creator info
     *
     * GET /social/accounts/{account_id}/tiktok/creator-info
     */
    public function tiktokCreatorInfo(string $accountId, array $options = []): array
    {
        return $this->client->request('GET', '/social/accounts/' . rawurlencode($accountId) . '/tiktok/creator-info', [
            'options' => $options,
        ]);
    }

    /**
     * Move account to profile
     *
     * POST /social/accounts/{account_id}/move
     */
    public function moveAccount(string $accountId, array $body, array $options = []): array
    {
        return $this->client->request('POST', '/social/accounts/' . rawurlencode($accountId) . '/move', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * List account groups
     *
     * GET /social/account-groups
     */
    public function listAccountGroups(array $options = []): array
    {
        return $this->client->request('GET', '/social/account-groups', [
            'options' => $options,
        ]);
    }

    /**
     * Create account group
     *
     * POST /social/account-groups
     */
    public function createAccountGroup(array $body, array $options = []): array
    {
        return $this->client->request('POST', '/social/account-groups', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Get account group
     *
     * GET /social/account-groups/{group_id}
     */
    public function getAccountGroup(string $groupId, array $options = []): array
    {
        return $this->client->request('GET', '/social/account-groups/' . rawurlencode($groupId), [
            'options' => $options,
        ]);
    }

    /**
     * Update account group
     *
     * PUT /social/account-groups/{group_id}
     */
    public function updateAccountGroup(string $groupId, array $body, array $options = []): array
    {
        return $this->client->request('PUT', '/social/account-groups/' . rawurlencode($groupId), [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Delete account group
     *
     * DELETE /social/account-groups/{group_id}
     */
    public function deleteAccountGroup(string $groupId, array $options = []): array
    {
        return $this->client->request('DELETE', '/social/account-groups/' . rawurlencode($groupId), [
            'options' => $options,
        ]);
    }

    /**
     * Get conversation
     *
     * GET /social/conversations/{conversation_id}
     */
    public function getConversation(string $conversationId, array $options = []): array
    {
        return $this->client->request('GET', '/social/conversations/' . rawurlencode($conversationId), [
            'options' => $options,
        ]);
    }

    /**
     * Archive / reopen conversation
     *
     * PATCH /social/conversations/{conversation_id}
     */
    public function updateConversation(string $conversationId, array $body, array $options = []): array
    {
        return $this->client->request('PATCH', '/social/conversations/' . rawurlencode($conversationId), [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Search conversations
     *
     * GET /social/conversations/search
     */
    public function searchConversations(array $query = [], array $options = []): array
    {
        return $this->client->request('GET', '/social/conversations/search', [
            'query' => $query,
            'options' => $options,
        ]);
    }

    /**
     * Pinterest boards
     *
     * GET /social/accounts/{account_id}/pinterest/boards
     */
    public function pinterestBoards(string $accountId, array $options = []): array
    {
        return $this->client->request('GET', '/social/accounts/' . rawurlencode($accountId) . '/pinterest/boards', [
            'options' => $options,
        ]);
    }

    /**
     * YouTube playlists
     *
     * GET /social/accounts/{account_id}/youtube/playlists
     */
    public function youtubePlaylists(string $accountId, array $options = []): array
    {
        return $this->client->request('GET', '/social/accounts/' . rawurlencode($accountId) . '/youtube/playlists', [
            'options' => $options,
        ]);
    }

    /**
     * Instagram publishing limit
     *
     * GET /social/accounts/{account_id}/instagram/publishing-limit
     */
    public function instagramPublishingLimit(string $accountId, array $options = []): array
    {
        return $this->client->request('GET', '/social/accounts/' . rawurlencode($accountId) . '/instagram/publishing-limit', [
            'options' => $options,
        ]);
    }

    /**
     * Google Business performance
     *
     * GET /social/accounts/{account_id}/gmb/performance
     */
    public function gmbPerformance(string $accountId, array $query = [], array $options = []): array
    {
        return $this->client->request('GET', '/social/accounts/' . rawurlencode($accountId) . '/gmb/performance', [
            'query' => $query,
            'options' => $options,
        ]);
    }

    /**
     * Google Business search keywords
     *
     * GET /social/accounts/{account_id}/gmb/search-keywords
     */
    public function gmbSearchKeywords(string $accountId, array $query = [], array $options = []): array
    {
        return $this->client->request('GET', '/social/accounts/' . rawurlencode($accountId) . '/gmb/search-keywords', [
            'query' => $query,
            'options' => $options,
        ]);
    }

    /**
     * Reddit search
     *
     * GET /social/accounts/{account_id}/reddit/search
     */
    public function redditSearch(string $accountId, array $query = [], array $options = []): array
    {
        return $this->client->request('GET', '/social/accounts/' . rawurlencode($accountId) . '/reddit/search', [
            'query' => $query,
            'options' => $options,
        ]);
    }

    /**
     * Reddit feed
     *
     * GET /social/accounts/{account_id}/reddit/feed
     */
    public function redditFeed(string $accountId, array $query = [], array $options = []): array
    {
        return $this->client->request('GET', '/social/accounts/' . rawurlencode($accountId) . '/reddit/feed', [
            'query' => $query,
            'options' => $options,
        ]);
    }

    /**
     * Subscribed subreddits
     *
     * GET /social/accounts/{account_id}/reddit/subreddits
     */
    public function redditSubreddits(string $accountId, array $options = []): array
    {
        return $this->client->request('GET', '/social/accounts/' . rawurlencode($accountId) . '/reddit/subreddits', [
            'options' => $options,
        ]);
    }

    /**
     * Subreddit rules
     *
     * GET /social/accounts/{account_id}/reddit/subreddits/{subreddit}/rules
     */
    public function redditSubredditRules(string $accountId, string $subreddit, array $options = []): array
    {
        return $this->client->request('GET', '/social/accounts/' . rawurlencode($accountId) . '/reddit/subreddits/' . rawurlencode($subreddit) . '/rules', [
            'options' => $options,
        ]);
    }

    /**
     * Instagram stories
     *
     * GET /social/accounts/{account_id}/instagram/stories
     */
    public function instagramStories(string $accountId, array $options = []): array
    {
        return $this->client->request('GET', '/social/accounts/' . rawurlencode($accountId) . '/instagram/stories', [
            'options' => $options,
        ]);
    }

    /**
     * Facebook post reactions
     *
     * GET /social/accounts/{account_id}/facebook/post-reactions
     */
    public function facebookPostReactions(string $accountId, array $query = [], array $options = []): array
    {
        return $this->client->request('GET', '/social/accounts/' . rawurlencode($accountId) . '/facebook/post-reactions', [
            'query' => $query,
            'options' => $options,
        ]);
    }

    /**
     * Instagram story insights
     *
     * GET /social/accounts/{account_id}/instagram/stories/{story_id}/insights
     */
    public function instagramStoryInsights(string $accountId, string $storyId, array $query = [], array $options = []): array
    {
        return $this->client->request('GET', '/social/accounts/' . rawurlencode($accountId) . '/instagram/stories/' . rawurlencode($storyId) . '/insights', [
            'query' => $query,
            'options' => $options,
        ]);
    }

    /**
     * Retweet on X
     *
     * POST /social/accounts/{account_id}/x/retweets
     */
    public function xRetweet(string $accountId, array $body, array $options = []): array
    {
        return $this->client->request('POST', '/social/accounts/' . rawurlencode($accountId) . '/x/retweets', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Undo retweet
     *
     * DELETE /social/accounts/{account_id}/x/retweets/{tweet_id}
     */
    public function xUnretweet(string $accountId, string $tweetId, array $options = []): array
    {
        return $this->client->request('DELETE', '/social/accounts/' . rawurlencode($accountId) . '/x/retweets/' . rawurlencode($tweetId), [
            'options' => $options,
        ]);
    }

    /**
     * Edit published post
     *
     * POST /social/posts/{post_id}/edit
     */
    public function editPublishedPost(string $postId, array $body, array $options = []): array
    {
        return $this->client->request('POST', '/social/posts/' . rawurlencode($postId) . '/edit', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Update YouTube metadata
     *
     * POST /social/posts/{post_id}/update-metadata
     */
    public function updatePostMetadata(string $postId, array $body, array $options = []): array
    {
        return $this->client->request('POST', '/social/posts/' . rawurlencode($postId) . '/update-metadata', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Sync external posts
     *
     * POST /social/posts/sync-external
     */
    public function syncExternalPosts(array $body, array $options = []): array
    {
        return $this->client->request('POST', '/social/posts/sync-external', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Live account insights
     *
     * GET /social/accounts/{account_id}/insights
     */
    public function accountInsights(string $accountId, array $options = []): array
    {
        return $this->client->request('GET', '/social/accounts/' . rawurlencode($accountId) . '/insights', [
            'options' => $options,
        ]);
    }

    /**
     * List Google locations
     *
     * GET /social/accounts/{account_id}/gmb/locations
     */
    public function gmbLocations(string $accountId, array $query = [], array $options = []): array
    {
        return $this->client->request('GET', '/social/accounts/' . rawurlencode($accountId) . '/gmb/locations', [
            'query' => $query,
            'options' => $options,
        ]);
    }

    /**
     * Get business info
     *
     * GET /social/accounts/{account_id}/gmb/location
     */
    public function gmbLocation(string $accountId, array $query = [], array $options = []): array
    {
        return $this->client->request('GET', '/social/accounts/' . rawurlencode($accountId) . '/gmb/location', [
            'query' => $query,
            'options' => $options,
        ]);
    }

    /**
     * Update business info
     *
     * PATCH /social/accounts/{account_id}/gmb/location
     */
    public function gmbUpdateLocation(string $accountId, array $body, array $options = []): array
    {
        return $this->client->request('PATCH', '/social/accounts/' . rawurlencode($accountId) . '/gmb/location', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Get attributes
     *
     * GET /social/accounts/{account_id}/gmb/attributes
     */
    public function gmbAttributes(string $accountId, array $options = []): array
    {
        return $this->client->request('GET', '/social/accounts/' . rawurlencode($accountId) . '/gmb/attributes', [
            'options' => $options,
        ]);
    }

    /**
     * Update attributes
     *
     * PUT /social/accounts/{account_id}/gmb/attributes
     */
    public function gmbUpdateAttributes(string $accountId, array $body, array $options = []): array
    {
        return $this->client->request('PUT', '/social/accounts/' . rawurlencode($accountId) . '/gmb/attributes', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Available attributes
     *
     * GET /social/accounts/{account_id}/gmb/attributes/metadata
     */
    public function gmbAttributeMetadata(string $accountId, array $options = []): array
    {
        return $this->client->request('GET', '/social/accounts/' . rawurlencode($accountId) . '/gmb/attributes/metadata', [
            'options' => $options,
        ]);
    }

    /**
     * List media
     *
     * GET /social/accounts/{account_id}/gmb/media
     */
    public function gmbMedia(string $accountId, array $options = []): array
    {
        return $this->client->request('GET', '/social/accounts/' . rawurlencode($accountId) . '/gmb/media', [
            'options' => $options,
        ]);
    }

    /**
     * Add photo
     *
     * POST /social/accounts/{account_id}/gmb/media
     */
    public function gmbCreateMedia(string $accountId, array $body, array $options = []): array
    {
        return $this->client->request('POST', '/social/accounts/' . rawurlencode($accountId) . '/gmb/media', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Delete media
     *
     * DELETE /social/accounts/{account_id}/gmb/media
     */
    public function gmbDeleteMedia(string $accountId, array $body, array $options = []): array
    {
        return $this->client->request('DELETE', '/social/accounts/' . rawurlencode($accountId) . '/gmb/media', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Get food menus
     *
     * GET /social/accounts/{account_id}/gmb/food-menus
     */
    public function gmbFoodMenus(string $accountId, array $options = []): array
    {
        return $this->client->request('GET', '/social/accounts/' . rawurlencode($accountId) . '/gmb/food-menus', [
            'options' => $options,
        ]);
    }

    /**
     * Update food menus
     *
     * PUT /social/accounts/{account_id}/gmb/food-menus
     */
    public function gmbUpdateFoodMenus(string $accountId, array $body, array $options = []): array
    {
        return $this->client->request('PUT', '/social/accounts/' . rawurlencode($accountId) . '/gmb/food-menus', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * List place-action links
     *
     * GET /social/accounts/{account_id}/gmb/place-actions
     */
    public function gmbPlaceActions(string $accountId, array $options = []): array
    {
        return $this->client->request('GET', '/social/accounts/' . rawurlencode($accountId) . '/gmb/place-actions', [
            'options' => $options,
        ]);
    }

    /**
     * Create place-action link
     *
     * POST /social/accounts/{account_id}/gmb/place-actions
     */
    public function gmbCreatePlaceAction(string $accountId, array $body, array $options = []): array
    {
        return $this->client->request('POST', '/social/accounts/' . rawurlencode($accountId) . '/gmb/place-actions', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Update place-action link
     *
     * PATCH /social/accounts/{account_id}/gmb/place-actions
     */
    public function gmbUpdatePlaceAction(string $accountId, array $body, array $options = []): array
    {
        return $this->client->request('PATCH', '/social/accounts/' . rawurlencode($accountId) . '/gmb/place-actions', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Delete place-action link
     *
     * DELETE /social/accounts/{account_id}/gmb/place-actions
     */
    public function gmbDeletePlaceAction(string $accountId, array $body, array $options = []): array
    {
        return $this->client->request('DELETE', '/social/accounts/' . rawurlencode($accountId) . '/gmb/place-actions', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * List verifications
     *
     * GET /social/accounts/{account_id}/gmb/verifications
     */
    public function gmbVerifications(string $accountId, array $options = []): array
    {
        return $this->client->request('GET', '/social/accounts/' . rawurlencode($accountId) . '/gmb/verifications', [
            'options' => $options,
        ]);
    }

    /**
     * Verification options
     *
     * POST /social/accounts/{account_id}/gmb/verifications/options
     */
    public function gmbVerificationOptions(string $accountId, array $body = [], array $options = []): array
    {
        return $this->client->request('POST', '/social/accounts/' . rawurlencode($accountId) . '/gmb/verifications/options', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Subreddit info + eligibility
     *
     * GET /social/accounts/{account_id}/reddit/subreddits/{subreddit}
     */
    public function redditSubredditInfo(string $accountId, string $subreddit, array $options = []): array
    {
        return $this->client->request('GET', '/social/accounts/' . rawurlencode($accountId) . '/reddit/subreddits/' . rawurlencode($subreddit), [
            'options' => $options,
        ]);
    }

    /**
     * X mentions
     *
     * GET /social/accounts/{account_id}/x/mentions
     */
    public function xMentions(string $accountId, array $query = [], array $options = []): array
    {
        return $this->client->request('GET', '/social/accounts/' . rawurlencode($accountId) . '/x/mentions', [
            'query' => $query,
            'options' => $options,
        ]);
    }
}
