<?php

// This file is auto-generated by scripts/generate-client.php. Do not edit by hand.

declare(strict_types=1);

namespace Smartlyq\Resources;

use Smartlyq\CoreClient;

/** Social endpoints. */
class SocialResource
{
    public function __construct(private readonly CoreClient $client)
    {
    }

    /**
     * List social accounts
     *
     * GET /social/accounts
     */
    public function listAccounts(array $options = []): array
    {
        return $this->client->request('GET', '/social/accounts', [
            'options' => $options,
        ]);
    }

    /**
     * List social posts
     *
     * GET /social/posts
     */
    public function listPosts(array $query = [], array $options = []): array
    {
        return $this->client->request('GET', '/social/posts', [
            'query' => $query,
            'options' => $options,
        ]);
    }

    /**
     * Create post (publish immediately)
     *
     * POST /social/posts
     */
    public function createPost(array $body, array $options = []): array
    {
        return $this->client->request('POST', '/social/posts', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Schedule post
     *
     * POST /social/posts/schedule
     */
    public function schedulePost(array $body, array $options = []): array
    {
        return $this->client->request('POST', '/social/posts/schedule', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Get social post
     *
     * GET /social/posts/{post_id}
     */
    public function getPost(string $postId, array $options = []): array
    {
        return $this->client->request('GET', '/social/posts/' . rawurlencode($postId), [
            'options' => $options,
        ]);
    }

    /**
     * Update social post
     *
     * PATCH /social/posts/{post_id}
     */
    public function updatePost(string $postId, array $body, array $options = []): array
    {
        return $this->client->request('PATCH', '/social/posts/' . rawurlencode($postId), [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Delete social post
     *
     * DELETE /social/posts/{post_id}
     */
    public function deletePost(string $postId, array $options = []): array
    {
        return $this->client->request('DELETE', '/social/posts/' . rawurlencode($postId), [
            'options' => $options,
        ]);
    }

    /**
     * Rename account
     *
     * PATCH /social/accounts/{account_id}
     */
    public function updateAccount(string $accountId, array $body, array $options = []): array
    {
        return $this->client->request('PATCH', '/social/accounts/' . rawurlencode($accountId), [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Account health
     *
     * GET /social/accounts/{account_id}/health
     */
    public function getAccountHealth(string $accountId, array $options = []): array
    {
        return $this->client->request('GET', '/social/accounts/' . rawurlencode($accountId) . '/health', [
            'options' => $options,
        ]);
    }

    /**
     * Account reconnect URL
     *
     * GET /social/accounts/{account_id}/reconnect-url
     */
    public function getAccountReconnectUrl(string $accountId, array $options = []): array
    {
        return $this->client->request('GET', '/social/accounts/' . rawurlencode($accountId) . '/reconnect-url', [
            'options' => $options,
        ]);
    }

    /**
     * Pause posting to an account
     *
     * POST /social/accounts/{account_id}/pause
     */
    public function pauseAccount(string $accountId, array $options = []): array
    {
        return $this->client->request('POST', '/social/accounts/' . rawurlencode($accountId) . '/pause', [
            'options' => $options,
        ]);
    }

    /**
     * Resume posting to an account
     *
     * POST /social/accounts/{account_id}/resume
     */
    public function resumeAccount(string $accountId, array $options = []): array
    {
        return $this->client->request('POST', '/social/accounts/' . rawurlencode($accountId) . '/resume', [
            'options' => $options,
        ]);
    }

    /**
     * Retry publishing a post
     *
     * POST /social/posts/{post_id}/retry
     */
    public function retryPost(string $postId, array $body, array $options = []): array
    {
        return $this->client->request('POST', '/social/posts/' . rawurlencode($postId) . '/retry', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Poll headless connection status
     *
     * GET /social/connect/{platform}
     */
    public function connectAccountStatus(string $platform, array $options = []): array
    {
        return $this->client->request('GET', '/social/connect/' . rawurlencode($platform), [
            'options' => $options,
        ]);
    }

    /**
     * Start headless account connection
     *
     * POST /social/connect/{platform}
     */
    public function connectAccount(string $platform, array $body = [], array $options = []): array
    {
        return $this->client->request('POST', '/social/connect/' . rawurlencode($platform), [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * List queues
     *
     * GET /social/queues
     */
    public function listQueues(array $options = []): array
    {
        return $this->client->request('GET', '/social/queues', [
            'options' => $options,
        ]);
    }

    /**
     * Create queue
     *
     * POST /social/queues
     */
    public function createQueue(array $body, array $options = []): array
    {
        return $this->client->request('POST', '/social/queues', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Get queue
     *
     * GET /social/queues/{queue_id}
     */
    public function getQueue(string $queueId, array $options = []): array
    {
        return $this->client->request('GET', '/social/queues/' . rawurlencode($queueId), [
            'options' => $options,
        ]);
    }

    /**
     * Update queue
     *
     * PUT /social/queues/{queue_id}
     */
    public function updateQueue(string $queueId, array $body, array $options = []): array
    {
        return $this->client->request('PUT', '/social/queues/' . rawurlencode($queueId), [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Delete queue
     *
     * DELETE /social/queues/{queue_id}
     */
    public function deleteQueue(string $queueId, array $options = []): array
    {
        return $this->client->request('DELETE', '/social/queues/' . rawurlencode($queueId), [
            'options' => $options,
        ]);
    }

    /**
     * Get next open slot
     *
     * GET /social/queues/{queue_id}/next-slot
     */
    public function getQueueNextSlot(string $queueId, array $options = []): array
    {
        return $this->client->request('GET', '/social/queues/' . rawurlencode($queueId) . '/next-slot', [
            'options' => $options,
        ]);
    }

    /**
     * Preview upcoming slots
     *
     * GET /social/queues/{queue_id}/preview
     */
    public function previewQueueSlots(string $queueId, array $query = [], array $options = []): array
    {
        return $this->client->request('GET', '/social/queues/' . rawurlencode($queueId) . '/preview', [
            'query' => $query,
            'options' => $options,
        ]);
    }

    /**
     * Unpublish post
     *
     * POST /social/posts/{post_id}/unpublish
     */
    public function unpublishPost(string $postId, array $body = [], array $options = []): array
    {
        return $this->client->request('POST', '/social/posts/' . rawurlencode($postId) . '/unpublish', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Validate post content
     *
     * POST /social/validate/post
     */
    public function validatePost(array $body, array $options = []): array
    {
        return $this->client->request('POST', '/social/validate/post', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Validate media URL
     *
     * POST /social/validate/media
     */
    public function validateMedia(array $body, array $options = []): array
    {
        return $this->client->request('POST', '/social/validate/media', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Stop recycling
     *
     * DELETE /social/posts/{post_id}/recycle
     */
    public function stopPostRecycle(string $postId, array $options = []): array
    {
        return $this->client->request('DELETE', '/social/posts/' . rawurlencode($postId) . '/recycle', [
            'options' => $options,
        ]);
    }

    /**
     * Bulk schedule posts
     *
     * POST /social/posts/bulk
     */
    public function bulkSchedulePosts(array $body, array $options = []): array
    {
        return $this->client->request('POST', '/social/posts/bulk', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Validate a bulk batch
     *
     * POST /social/posts/bulk/validate
     */
    public function validateBulkBatch(array $body, array $options = []): array
    {
        return $this->client->request('POST', '/social/posts/bulk/validate', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Bulk account health
     *
     * GET /social/accounts/health
     */
    public function bulkAccountHealth(array $options = []): array
    {
        return $this->client->request('GET', '/social/accounts/health', [
            'options' => $options,
        ]);
    }

    /**
     * Follower stats
     *
     * GET /social/accounts/follower-stats
     */
    public function accountFollowerStats(array $query = [], array $options = []): array
    {
        return $this->client->request('GET', '/social/accounts/follower-stats', [
            'query' => $query,
            'options' => $options,
        ]);
    }

    /**
     * TikTok creator info
     *
     * GET /social/accounts/{account_id}/tiktok/creator-info
     */
    public function tiktokCreatorInfo(string $accountId, array $options = []): array
    {
        return $this->client->request('GET', '/social/accounts/' . rawurlencode($accountId) . '/tiktok/creator-info', [
            'options' => $options,
        ]);
    }

    /**
     * Move account to profile
     *
     * POST /social/accounts/{account_id}/move
     */
    public function moveAccount(string $accountId, array $body, array $options = []): array
    {
        return $this->client->request('POST', '/social/accounts/' . rawurlencode($accountId) . '/move', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * List account groups
     *
     * GET /social/account-groups
     */
    public function listAccountGroups(array $options = []): array
    {
        return $this->client->request('GET', '/social/account-groups', [
            'options' => $options,
        ]);
    }

    /**
     * Create account group
     *
     * POST /social/account-groups
     */
    public function createAccountGroup(array $body, array $options = []): array
    {
        return $this->client->request('POST', '/social/account-groups', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Get account group
     *
     * GET /social/account-groups/{group_id}
     */
    public function getAccountGroup(string $groupId, array $options = []): array
    {
        return $this->client->request('GET', '/social/account-groups/' . rawurlencode($groupId), [
            'options' => $options,
        ]);
    }

    /**
     * Update account group
     *
     * PUT /social/account-groups/{group_id}
     */
    public function updateAccountGroup(string $groupId, array $body, array $options = []): array
    {
        return $this->client->request('PUT', '/social/account-groups/' . rawurlencode($groupId), [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Delete account group
     *
     * DELETE /social/account-groups/{group_id}
     */
    public function deleteAccountGroup(string $groupId, array $options = []): array
    {
        return $this->client->request('DELETE', '/social/account-groups/' . rawurlencode($groupId), [
            'options' => $options,
        ]);
    }
}
