<?php

// This file is auto-generated by scripts/generate-client.php. Do not edit by hand.

declare(strict_types=1);

namespace Smartlyq\Resources;

use Smartlyq\CoreClient;

/** Social endpoints. */
class SocialResource
{
    public function __construct(private readonly CoreClient $client)
    {
    }

    /**
     * List social accounts
     *
     * GET /social/accounts
     */
    public function listAccounts(array $options = []): array
    {
        return $this->client->request('GET', '/social/accounts', [
            'options' => $options,
        ]);
    }

    /**
     * List social posts
     *
     * GET /social/posts
     */
    public function listPosts(array $query = [], array $options = []): array
    {
        return $this->client->request('GET', '/social/posts', [
            'query' => $query,
            'options' => $options,
        ]);
    }

    /**
     * Create post (publish immediately)
     *
     * POST /social/posts
     */
    public function createPost(array $body, array $options = []): array
    {
        return $this->client->request('POST', '/social/posts', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Schedule post
     *
     * POST /social/posts/schedule
     */
    public function schedulePost(array $body, array $options = []): array
    {
        return $this->client->request('POST', '/social/posts/schedule', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Get social post
     *
     * GET /social/posts/{post_id}
     */
    public function getPost(string $postId, array $options = []): array
    {
        return $this->client->request('GET', '/social/posts/' . rawurlencode($postId), [
            'options' => $options,
        ]);
    }

    /**
     * Update social post
     *
     * PATCH /social/posts/{post_id}
     */
    public function updatePost(string $postId, array $body, array $options = []): array
    {
        return $this->client->request('PATCH', '/social/posts/' . rawurlencode($postId), [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Delete social post
     *
     * DELETE /social/posts/{post_id}
     */
    public function deletePost(string $postId, array $options = []): array
    {
        return $this->client->request('DELETE', '/social/posts/' . rawurlencode($postId), [
            'options' => $options,
        ]);
    }

    /**
     * Disconnect a social account
     *
     * DELETE /social/accounts/{account_id}
     */
    public function disconnectAccount(string $accountId, array $options = []): array
    {
        return $this->client->request('DELETE', '/social/accounts/' . rawurlencode($accountId), [
            'options' => $options,
        ]);
    }

    /**
     * Account health
     *
     * GET /social/accounts/{account_id}/health
     */
    public function getAccountHealth(string $accountId, array $options = []): array
    {
        return $this->client->request('GET', '/social/accounts/' . rawurlencode($accountId) . '/health', [
            'options' => $options,
        ]);
    }

    /**
     * Account reconnect URL
     *
     * GET /social/accounts/{account_id}/reconnect-url
     */
    public function getAccountReconnectUrl(string $accountId, array $options = []): array
    {
        return $this->client->request('GET', '/social/accounts/' . rawurlencode($accountId) . '/reconnect-url', [
            'options' => $options,
        ]);
    }

    /**
     * Pause posting to an account
     *
     * POST /social/accounts/{account_id}/pause
     */
    public function pauseAccount(string $accountId, array $options = []): array
    {
        return $this->client->request('POST', '/social/accounts/' . rawurlencode($accountId) . '/pause', [
            'options' => $options,
        ]);
    }

    /**
     * Resume posting to an account
     *
     * POST /social/accounts/{account_id}/resume
     */
    public function resumeAccount(string $accountId, array $options = []): array
    {
        return $this->client->request('POST', '/social/accounts/' . rawurlencode($accountId) . '/resume', [
            'options' => $options,
        ]);
    }

    /**
     * Retry publishing a post
     *
     * POST /social/posts/{post_id}/retry
     */
    public function retryPost(string $postId, array $body, array $options = []): array
    {
        return $this->client->request('POST', '/social/posts/' . rawurlencode($postId) . '/retry', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Poll headless connection status
     *
     * GET /social/connect/{platform}
     */
    public function connectAccountStatus(string $platform, array $options = []): array
    {
        return $this->client->request('GET', '/social/connect/' . rawurlencode($platform), [
            'options' => $options,
        ]);
    }

    /**
     * Start headless account connection
     *
     * POST /social/connect/{platform}
     */
    public function connectAccount(string $platform, array $body = [], array $options = []): array
    {
        return $this->client->request('POST', '/social/connect/' . rawurlencode($platform), [
            'body' => $body,
            'options' => $options,
        ]);
    }
}
