<?php

// This file is auto-generated by scripts/generate-client.php. Do not edit by hand.

declare(strict_types=1);

namespace Smartlyq\Resources;

use Smartlyq\CoreClient;

/** URLs endpoints. */
class UrlsResource
{
    public function __construct(private readonly CoreClient $client)
    {
    }

    /**
     * Shorten URL
     *
     * POST /urls/shorten
     */
    public function shorten(array $body, array $options = []): array
    {
        return $this->client->request('POST', '/urls/shorten', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * List short URLs
     *
     * GET /urls
     */
    public function list(array $query = [], array $options = []): array
    {
        return $this->client->request('GET', '/urls', [
            'query' => $query,
            'options' => $options,
        ]);
    }

    /**
     * Get short URL
     *
     * GET /urls/{url_id}
     */
    public function get(string $urlId, array $options = []): array
    {
        return $this->client->request('GET', '/urls/' . rawurlencode($urlId), [
            'options' => $options,
        ]);
    }

    /**
     * Delete short URL
     *
     * DELETE /urls/{url_id}
     */
    public function delete(string $urlId, array $options = []): array
    {
        return $this->client->request('DELETE', '/urls/' . rawurlencode($urlId), [
            'options' => $options,
        ]);
    }

    /**
     * Get short URL stats
     *
     * GET /urls/{url_id}/stats
     */
    public function getStats(string $urlId, array $options = []): array
    {
        return $this->client->request('GET', '/urls/' . rawurlencode($urlId) . '/stats', [
            'options' => $options,
        ]);
    }
}
