<?php

// This file is auto-generated by scripts/generate-client.php. Do not edit by hand.

declare(strict_types=1);

namespace Smartlyq\Resources;

use Smartlyq\CoreClient;

/** Videos endpoints. */
class VideosResource
{
    public function __construct(private readonly CoreClient $client)
    {
    }

    /**
     * List available video models
     *
     * GET /videos/models
     */
    public function listModels(array $options = []): array
    {
        return $this->client->request('GET', '/videos/models', [
            'options' => $options,
        ]);
    }

    /**
     * Generate video
     *
     * POST /videos/generate
     */
    public function generate(array $body, array $options = []): array
    {
        return $this->client->request('POST', '/videos/generate', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * List videos
     *
     * GET /videos
     */
    public function list(array $query = [], array $options = []): array
    {
        return $this->client->request('GET', '/videos', [
            'query' => $query,
            'options' => $options,
        ]);
    }

    /**
     * Get video
     *
     * GET /videos/{video_id}
     */
    public function get(string $videoId, array $options = []): array
    {
        return $this->client->request('GET', '/videos/' . rawurlencode($videoId), [
            'options' => $options,
        ]);
    }

    /**
     * Delete video
     *
     * DELETE /videos/{video_id}
     */
    public function delete(string $videoId, array $options = []): array
    {
        return $this->client->request('DELETE', '/videos/' . rawurlencode($videoId), [
            'options' => $options,
        ]);
    }

    /**
     * Generate a viral hook line
     *
     * POST /videos/hook
     */
    public function generateHook(array $body = [], array $options = []): array
    {
        return $this->client->request('POST', '/videos/hook', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Suggest B-roll moments
     *
     * POST /videos/broll-suggest
     */
    public function suggestBroll(array $body, array $options = []): array
    {
        return $this->client->request('POST', '/videos/broll-suggest', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Suggest on-screen emphasis
     *
     * POST /videos/emphasis
     */
    public function suggestEmphasis(array $body, array $options = []): array
    {
        return $this->client->request('POST', '/videos/emphasis', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Generate a viral thumbnail
     *
     * POST /videos/viral-thumbnail
     */
    public function generateViralThumbnail(array $body, array $options = []): array
    {
        return $this->client->request('POST', '/videos/viral-thumbnail', [
            'body' => $body,
            'options' => $options,
        ]);
    }
}
