<?php

// This file is auto-generated by scripts/generate-client.php. Do not edit by hand.

declare(strict_types=1);

namespace Smartlyq\Resources;

use Smartlyq\CoreClient;

/** Webhooks endpoints. */
class WebhooksResource
{
    public function __construct(private readonly CoreClient $client)
    {
    }

    /**
     * List webhooks
     *
     * GET /webhooks
     */
    public function list(array $options = []): array
    {
        return $this->client->request('GET', '/webhooks', [
            'options' => $options,
        ]);
    }

    /**
     * Create webhook
     *
     * POST /webhooks
     */
    public function create(array $body, array $options = []): array
    {
        return $this->client->request('POST', '/webhooks', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Delete webhook
     *
     * DELETE /webhooks/{id}
     */
    public function delete(string $id, array $options = []): array
    {
        return $this->client->request('DELETE', '/webhooks/' . rawurlencode($id), [
            'options' => $options,
        ]);
    }
}
