<?php

// This file is auto-generated by scripts/generate-client.php. Do not edit by hand.

declare(strict_types=1);

namespace Smartlyq\Resources;

use Smartlyq\CoreClient;

/** Webhooks endpoints. */
class WebhooksResource
{
    public function __construct(private readonly CoreClient $client)
    {
    }

    /**
     * List webhooks
     *
     * GET /webhooks
     */
    public function list(array $options = []): array
    {
        return $this->client->request('GET', '/webhooks', [
            'options' => $options,
        ]);
    }

    /**
     * Create webhook
     *
     * POST /webhooks
     */
    public function create(array $body, array $options = []): array
    {
        return $this->client->request('POST', '/webhooks', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Update webhook
     *
     * PUT /webhooks/{id}
     */
    public function update(string $id, array $body, array $options = []): array
    {
        return $this->client->request('PUT', '/webhooks/' . rawurlencode($id), [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Delete webhook
     *
     * DELETE /webhooks/{id}
     */
    public function delete(string $id, array $options = []): array
    {
        return $this->client->request('DELETE', '/webhooks/' . rawurlencode($id), [
            'options' => $options,
        ]);
    }

    /**
     * List webhook delivery logs
     *
     * GET /webhooks/logs
     */
    public function listLogs(array $query = [], array $options = []): array
    {
        return $this->client->request('GET', '/webhooks/logs', [
            'query' => $query,
            'options' => $options,
        ]);
    }

    /**
     * Send test webhook
     *
     * POST /webhooks/{id}/test
     */
    public function test(string $id, array $options = []): array
    {
        return $this->client->request('POST', '/webhooks/' . rawurlencode($id) . '/test', [
            'options' => $options,
        ]);
    }

    /**
     * Replay a webhook delivery
     *
     * POST /webhooks/deliveries/{id}/replay
     */
    public function replayDelivery(string $id, array $options = []): array
    {
        return $this->client->request('POST', '/webhooks/deliveries/' . rawurlencode($id) . '/replay', [
            'options' => $options,
        ]);
    }
}
