<?php

// This file is auto-generated by scripts/generate-client.php. Do not edit by hand.

declare(strict_types=1);

namespace Smartlyq\Resources;

use Smartlyq\CoreClient;

/** WhatsApp endpoints. */
class WhatsAppResource
{
    public function __construct(private readonly CoreClient $client)
    {
    }

    /**
     * Send a WhatsApp message
     *
     * POST /whatsapp/messages
     */
    public function sendWhatsAppMessage(array $body, array $options = []): array
    {
        return $this->client->request('POST', '/whatsapp/messages', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * List message templates
     *
     * GET /whatsapp/templates
     */
    public function listWhatsAppTemplates(array $query = [], array $options = []): array
    {
        return $this->client->request('GET', '/whatsapp/templates', [
            'query' => $query,
            'options' => $options,
        ]);
    }

    /**
     * Create a message template
     *
     * POST /whatsapp/templates
     */
    public function createWhatsAppTemplate(array $body, array $options = []): array
    {
        return $this->client->request('POST', '/whatsapp/templates', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Get business profile
     *
     * GET /whatsapp/business-profile
     */
    public function getWhatsAppBusinessProfile(array $query = [], array $options = []): array
    {
        return $this->client->request('GET', '/whatsapp/business-profile', [
            'query' => $query,
            'options' => $options,
        ]);
    }

    /**
     * Update business profile
     *
     * PATCH /whatsapp/business-profile
     */
    public function updateWhatsAppBusinessProfile(array $body, array $options = []): array
    {
        return $this->client->request('PATCH', '/whatsapp/business-profile', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * List phone numbers
     *
     * GET /whatsapp/phone-numbers
     */
    public function listWhatsAppPhoneNumbers(array $query = [], array $options = []): array
    {
        return $this->client->request('GET', '/whatsapp/phone-numbers', [
            'query' => $query,
            'options' => $options,
        ]);
    }

    /**
     * List flows
     *
     * GET /whatsapp/flows
     */
    public function listWhatsAppFlows(array $query = [], array $options = []): array
    {
        return $this->client->request('GET', '/whatsapp/flows', [
            'query' => $query,
            'options' => $options,
        ]);
    }

    /**
     * Create a flow
     *
     * POST /whatsapp/flows
     */
    public function createWhatsAppFlow(array $body, array $options = []): array
    {
        return $this->client->request('POST', '/whatsapp/flows', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Get flow
     *
     * GET /whatsapp/flows/{flow_id}
     */
    public function getWhatsAppFlow(string $flowId, array $query = [], array $options = []): array
    {
        return $this->client->request('GET', '/whatsapp/flows/' . rawurlencode($flowId), [
            'query' => $query,
            'options' => $options,
        ]);
    }

    /**
     * Update flow
     *
     * PATCH /whatsapp/flows/{flow_id}
     */
    public function updateWhatsAppFlow(string $flowId, array $body, array $options = []): array
    {
        return $this->client->request('PATCH', '/whatsapp/flows/' . rawurlencode($flowId), [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Delete flow
     *
     * DELETE /whatsapp/flows/{flow_id}
     */
    public function deleteWhatsAppFlow(string $flowId, array $query = [], array $options = []): array
    {
        return $this->client->request('DELETE', '/whatsapp/flows/' . rawurlencode($flowId), [
            'query' => $query,
            'options' => $options,
        ]);
    }

    /**
     * Get flow JSON asset
     *
     * GET /whatsapp/flows/{flow_id}/json
     */
    public function getWhatsAppFlowJson(string $flowId, array $query = [], array $options = []): array
    {
        return $this->client->request('GET', '/whatsapp/flows/' . rawurlencode($flowId) . '/json', [
            'query' => $query,
            'options' => $options,
        ]);
    }

    /**
     * Upload flow JSON
     *
     * PUT /whatsapp/flows/{flow_id}/json
     */
    public function uploadWhatsAppFlowJson(string $flowId, array $body, array $options = []): array
    {
        return $this->client->request('PUT', '/whatsapp/flows/' . rawurlencode($flowId) . '/json', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Get flow preview URL
     *
     * GET /whatsapp/flows/{flow_id}/preview
     */
    public function getWhatsAppFlowPreview(string $flowId, array $query = [], array $options = []): array
    {
        return $this->client->request('GET', '/whatsapp/flows/' . rawurlencode($flowId) . '/preview', [
            'query' => $query,
            'options' => $options,
        ]);
    }

    /**
     * Publish flow
     *
     * POST /whatsapp/flows/{flow_id}/publish
     */
    public function publishWhatsAppFlow(string $flowId, array $body, array $options = []): array
    {
        return $this->client->request('POST', '/whatsapp/flows/' . rawurlencode($flowId) . '/publish', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Deprecate flow
     *
     * POST /whatsapp/flows/{flow_id}/deprecate
     */
    public function deprecateWhatsAppFlow(string $flowId, array $body, array $options = []): array
    {
        return $this->client->request('POST', '/whatsapp/flows/' . rawurlencode($flowId) . '/deprecate', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * List blocked users
     *
     * GET /whatsapp/block-users
     */
    public function getWhatsAppBlockedUsers(array $query = [], array $options = []): array
    {
        return $this->client->request('GET', '/whatsapp/block-users', [
            'query' => $query,
            'options' => $options,
        ]);
    }

    /**
     * Block users
     *
     * POST /whatsapp/block-users
     */
    public function blockWhatsAppUsers(array $body, array $options = []): array
    {
        return $this->client->request('POST', '/whatsapp/block-users', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Unblock users
     *
     * DELETE /whatsapp/block-users
     */
    public function unblockWhatsAppUsers(array $body, array $options = []): array
    {
        return $this->client->request('DELETE', '/whatsapp/block-users', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Get a WhatsApp template
     *
     * GET /whatsapp/templates/{name}
     */
    public function getTemplate(string $name, array $query = [], array $options = []): array
    {
        return $this->client->request('GET', '/whatsapp/templates/' . rawurlencode($name), [
            'query' => $query,
            'options' => $options,
        ]);
    }

    /**
     * Update a WhatsApp template
     *
     * PATCH /whatsapp/templates/{name}
     */
    public function updateTemplate(string $name, array $body, array $options = []): array
    {
        return $this->client->request('PATCH', '/whatsapp/templates/' . rawurlencode($name), [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Delete a WhatsApp template
     *
     * DELETE /whatsapp/templates/{name}
     */
    public function deleteTemplate(string $name, array $query = [], array $options = []): array
    {
        return $this->client->request('DELETE', '/whatsapp/templates/' . rawurlencode($name), [
            'query' => $query,
            'options' => $options,
        ]);
    }

    /**
     * Set the WhatsApp profile photo
     *
     * POST /whatsapp/business-profile/photo
     */
    public function updateProfilePhoto(array $body, array $options = []): array
    {
        return $this->client->request('POST', '/whatsapp/business-profile/photo', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Get the WhatsApp display name
     *
     * GET /whatsapp/business-profile/display-name
     */
    public function getDisplayName(array $query = [], array $options = []): array
    {
        return $this->client->request('GET', '/whatsapp/business-profile/display-name', [
            'query' => $query,
            'options' => $options,
        ]);
    }

    /**
     * Request a WhatsApp display-name change
     *
     * POST /whatsapp/business-profile/display-name
     */
    public function updateDisplayName(array $body, array $options = []): array
    {
        return $this->client->request('POST', '/whatsapp/business-profile/display-name', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Browse the shared template library
     *
     * GET /whatsapp/template-library
     */
    public function listTemplateLibrary(array $query = [], array $options = []): array
    {
        return $this->client->request('GET', '/whatsapp/template-library', [
            'query' => $query,
            'options' => $options,
        ]);
    }

    /**
     * Adopt a library template
     *
     * POST /whatsapp/templates/from-library
     */
    public function createTemplateFromLibrary(array $body, array $options = []): array
    {
        return $this->client->request('POST', '/whatsapp/templates/from-library', [
            'body' => $body,
            'options' => $options,
        ]);
    }
}
