<?php

// This file is auto-generated by scripts/generate-client.php. Do not edit by hand.

declare(strict_types=1);

namespace Smartlyq\Resources;

use Smartlyq\CoreClient;

/** WhatsApp endpoints. */
class WhatsAppResource
{
    public function __construct(private readonly CoreClient $client)
    {
    }

    /**
     * Send a WhatsApp message
     *
     * POST /whatsapp/messages
     */
    public function sendWhatsAppMessage(array $body, array $options = []): array
    {
        return $this->client->request('POST', '/whatsapp/messages', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * List message templates
     *
     * GET /whatsapp/templates
     */
    public function listWhatsAppTemplates(array $query = [], array $options = []): array
    {
        return $this->client->request('GET', '/whatsapp/templates', [
            'query' => $query,
            'options' => $options,
        ]);
    }

    /**
     * Create a message template
     *
     * POST /whatsapp/templates
     */
    public function createWhatsAppTemplate(array $body, array $options = []): array
    {
        return $this->client->request('POST', '/whatsapp/templates', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Get business profile
     *
     * GET /whatsapp/business-profile
     */
    public function getWhatsAppBusinessProfile(array $query = [], array $options = []): array
    {
        return $this->client->request('GET', '/whatsapp/business-profile', [
            'query' => $query,
            'options' => $options,
        ]);
    }

    /**
     * Update business profile
     *
     * PATCH /whatsapp/business-profile
     */
    public function updateWhatsAppBusinessProfile(array $body, array $options = []): array
    {
        return $this->client->request('PATCH', '/whatsapp/business-profile', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * List phone numbers
     *
     * GET /whatsapp/phone-numbers
     */
    public function listWhatsAppPhoneNumbers(array $query = [], array $options = []): array
    {
        return $this->client->request('GET', '/whatsapp/phone-numbers', [
            'query' => $query,
            'options' => $options,
        ]);
    }

    /**
     * Get a WhatsApp template
     *
     * GET /whatsapp/templates/{name}
     */
    public function getTemplate(string $name, array $query = [], array $options = []): array
    {
        return $this->client->request('GET', '/whatsapp/templates/' . rawurlencode($name), [
            'query' => $query,
            'options' => $options,
        ]);
    }

    /**
     * Update a WhatsApp template
     *
     * PATCH /whatsapp/templates/{name}
     */
    public function updateTemplate(string $name, array $body, array $options = []): array
    {
        return $this->client->request('PATCH', '/whatsapp/templates/' . rawurlencode($name), [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Delete a WhatsApp template
     *
     * DELETE /whatsapp/templates/{name}
     */
    public function deleteTemplate(string $name, array $query = [], array $options = []): array
    {
        return $this->client->request('DELETE', '/whatsapp/templates/' . rawurlencode($name), [
            'query' => $query,
            'options' => $options,
        ]);
    }

    /**
     * Set the WhatsApp profile photo
     *
     * POST /whatsapp/business-profile/photo
     */
    public function updateProfilePhoto(array $body, array $options = []): array
    {
        return $this->client->request('POST', '/whatsapp/business-profile/photo', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Get the WhatsApp display name
     *
     * GET /whatsapp/business-profile/display-name
     */
    public function getDisplayName(array $query = [], array $options = []): array
    {
        return $this->client->request('GET', '/whatsapp/business-profile/display-name', [
            'query' => $query,
            'options' => $options,
        ]);
    }

    /**
     * Request a WhatsApp display-name change
     *
     * POST /whatsapp/business-profile/display-name
     */
    public function updateDisplayName(array $body, array $options = []): array
    {
        return $this->client->request('POST', '/whatsapp/business-profile/display-name', [
            'body' => $body,
            'options' => $options,
        ]);
    }
}
