<?php

// This file is auto-generated by scripts/generate-client.php. Do not edit by hand.

declare(strict_types=1);

namespace Smartlyq\Resources;

use Smartlyq\CoreClient;

/** Workspaces endpoints. */
class WorkspacesResource
{
    public function __construct(private readonly CoreClient $client)
    {
    }

    /**
     * List workspaces (sub-accounts)
     *
     * GET /workspaces
     */
    public function list(array $options = []): array
    {
        return $this->client->request('GET', '/workspaces', [
            'options' => $options,
        ]);
    }

    /**
     * Create a workspace (sub-account)
     *
     * POST /workspaces
     */
    public function create(array $body, array $options = []): array
    {
        return $this->client->request('POST', '/workspaces', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Bulk sub-account action
     *
     * POST /workspaces/bulk
     */
    public function bulkAction(array $body, array $options = []): array
    {
        return $this->client->request('POST', '/workspaces/bulk', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Get a workspace (sub-account)
     *
     * GET /workspaces/{id}
     */
    public function get(string $id, array $options = []): array
    {
        return $this->client->request('GET', '/workspaces/' . rawurlencode($id), [
            'options' => $options,
        ]);
    }

    /**
     * Delete a workspace (sub-account)
     *
     * DELETE /workspaces/{id}
     */
    public function delete(string $id, array $body, array $options = []): array
    {
        return $this->client->request('DELETE', '/workspaces/' . rawurlencode($id), [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Disable SaaS mode for a workspace
     *
     * POST /workspaces/{id}/disable-saas
     */
    public function disableSaas(string $id, array $body = [], array $options = []): array
    {
        return $this->client->request('POST', '/workspaces/' . rawurlencode($id) . '/disable-saas', [
            'body' => $body,
            'options' => $options,
        ]);
    }

    /**
     * Pause (suspend) a workspace
     *
     * POST /workspaces/{id}/pause
     */
    public function pause(string $id, array $options = []): array
    {
        return $this->client->request('POST', '/workspaces/' . rawurlencode($id) . '/pause', [
            'options' => $options,
        ]);
    }

    /**
     * Resume a paused workspace
     *
     * POST /workspaces/{id}/resume
     */
    public function resume(string $id, array $options = []): array
    {
        return $this->client->request('POST', '/workspaces/' . rawurlencode($id) . '/resume', [
            'options' => $options,
        ]);
    }

    /**
     * Get a sub-account's subscription
     *
     * GET /workspaces/{id}/subscription
     */
    public function getSubscription(string $id, array $options = []): array
    {
        return $this->client->request('GET', '/workspaces/' . rawurlencode($id) . '/subscription', [
            'options' => $options,
        ]);
    }

    /**
     * Get a sub-account's wallet balance
     *
     * GET /workspaces/{id}/wallet
     */
    public function getWallet(string $id, array $options = []): array
    {
        return $this->client->request('GET', '/workspaces/' . rawurlencode($id) . '/wallet', [
            'options' => $options,
        ]);
    }

    /**
     * List SaaS plans
     *
     * GET /saas/plans
     */
    public function listSaasPlans(array $options = []): array
    {
        return $this->client->request('GET', '/saas/plans', [
            'options' => $options,
        ]);
    }

    /**
     * Get a SaaS plan
     *
     * GET /saas/plans/{id}
     */
    public function getSaasPlan(string $id, array $options = []): array
    {
        return $this->client->request('GET', '/saas/plans/' . rawurlencode($id), [
            'options' => $options,
        ]);
    }
}
