<?php

// This file is auto-generated by scripts/generate-tests.php. Do not edit by hand.

declare(strict_types=1);

use PHPUnit\Framework\TestCase;
use Smartlyq\SmartlyQ;

final class EndpointsGeneratedTest extends TestCase
{
    /** @var list<array{method: string, path: string}> */
    private array $calls = [];

    private function client(): SmartlyQ
    {
        $this->calls = [];
        $transport = function (string $method, string $url, array $headers, ?string $body, float $timeout): array {
            $path = (string) parse_url($url, PHP_URL_PATH);
            if (str_starts_with($path, '/v1')) {
                $path = substr($path, 3);
            }
            $this->calls[] = ['method' => $method, 'path' => $path];

            return [
                'status' => 200,
                'headers' => ['content-type' => 'application/json'],
                'body' => '{"success":true,"data":{}}',
            ];
        };

        return new SmartlyQ('sqk_test_xxxxxxxxxxxx', ['transport' => $transport, 'max_retries' => 0]);
    }

    public function test_account_getMe(): void
    {
        $sq = $this->client();
        $sq->account->getMe();
        $this->assertSame(['method' => 'GET', 'path' => '/me'], $this->calls[0]);
    }

    public function test_account_getMeUsage(): void
    {
        $sq = $this->client();
        $sq->account->getMeUsage();
        $this->assertSame(['method' => 'GET', 'path' => '/me/usage'], $this->calls[0]);
    }

    public function test_account_getMeBalance(): void
    {
        $sq = $this->client();
        $sq->account->getMeBalance();
        $this->assertSame(['method' => 'GET', 'path' => '/me/balance'], $this->calls[0]);
    }

    public function test_account_getBilling(): void
    {
        $sq = $this->client();
        $sq->account->getBilling();
        $this->assertSame(['method' => 'GET', 'path' => '/me/billing'], $this->calls[0]);
    }

    public function test_captain_sendMessage(): void
    {
        $sq = $this->client();
        $sq->captain->sendMessage([]);
        $this->assertSame(['method' => 'POST', 'path' => '/captain/messages'], $this->calls[0]);
    }

    public function test_captain_listConversations(): void
    {
        $sq = $this->client();
        $sq->captain->listConversations();
        $this->assertSame(['method' => 'GET', 'path' => '/captain/conversations'], $this->calls[0]);
    }

    public function test_captain_getConversation(): void
    {
        $sq = $this->client();
        $sq->captain->getConversation('test-id');
        $this->assertSame(['method' => 'GET', 'path' => '/captain/conversations/test-id'], $this->calls[0]);
    }

    public function test_analytics_getOverview(): void
    {
        $sq = $this->client();
        $sq->analytics->getOverview();
        $this->assertSame(['method' => 'GET', 'path' => '/analytics/overview'], $this->calls[0]);
    }

    public function test_analytics_getPosts(): void
    {
        $sq = $this->client();
        $sq->analytics->getPosts();
        $this->assertSame(['method' => 'GET', 'path' => '/analytics/posts'], $this->calls[0]);
    }

    public function test_analytics_getAccount(): void
    {
        $sq = $this->client();
        $sq->analytics->getAccount('test-id');
        $this->assertSame(['method' => 'GET', 'path' => '/analytics/accounts/test-id'], $this->calls[0]);
    }

    public function test_analytics_dailyMetrics(): void
    {
        $sq = $this->client();
        $sq->analytics->dailyMetrics();
        $this->assertSame(['method' => 'GET', 'path' => '/analytics/daily-metrics'], $this->calls[0]);
    }

    public function test_analytics_bestTime(): void
    {
        $sq = $this->client();
        $sq->analytics->bestTime();
        $this->assertSame(['method' => 'GET', 'path' => '/analytics/best-time'], $this->calls[0]);
    }

    public function test_analytics_contentDecay(): void
    {
        $sq = $this->client();
        $sq->analytics->contentDecay();
        $this->assertSame(['method' => 'GET', 'path' => '/analytics/content-decay'], $this->calls[0]);
    }

    public function test_analytics_postingFrequency(): void
    {
        $sq = $this->client();
        $sq->analytics->postingFrequency();
        $this->assertSame(['method' => 'GET', 'path' => '/analytics/posting-frequency'], $this->calls[0]);
    }

    public function test_analytics_postTimeline(): void
    {
        $sq = $this->client();
        $sq->analytics->postTimeline('test-id');
        $this->assertSame(['method' => 'GET', 'path' => '/analytics/posts/test-id/timeline'], $this->calls[0]);
    }

    public function test_analytics_inboxVolume(): void
    {
        $sq = $this->client();
        $sq->analytics->inboxVolume();
        $this->assertSame(['method' => 'GET', 'path' => '/analytics/inbox/volume'], $this->calls[0]);
    }

    public function test_analytics_inboxHeatmap(): void
    {
        $sq = $this->client();
        $sq->analytics->inboxHeatmap();
        $this->assertSame(['method' => 'GET', 'path' => '/analytics/inbox/heatmap'], $this->calls[0]);
    }

    public function test_analytics_inboxSourceBreakdown(): void
    {
        $sq = $this->client();
        $sq->analytics->inboxSourceBreakdown();
        $this->assertSame(['method' => 'GET', 'path' => '/analytics/inbox/source-breakdown'], $this->calls[0]);
    }

    public function test_analytics_inboxResponseTime(): void
    {
        $sq = $this->client();
        $sq->analytics->inboxResponseTime();
        $this->assertSame(['method' => 'GET', 'path' => '/analytics/inbox/response-time'], $this->calls[0]);
    }

    public function test_analytics_inboxTopAccounts(): void
    {
        $sq = $this->client();
        $sq->analytics->inboxTopAccounts();
        $this->assertSame(['method' => 'GET', 'path' => '/analytics/inbox/top-accounts'], $this->calls[0]);
    }

    public function test_analytics_inboxConversations(): void
    {
        $sq = $this->client();
        $sq->analytics->inboxConversations();
        $this->assertSame(['method' => 'GET', 'path' => '/analytics/inbox/conversations'], $this->calls[0]);
    }

    public function test_analytics_inboxConversationDetail(): void
    {
        $sq = $this->client();
        $sq->analytics->inboxConversationDetail('test-id');
        $this->assertSame(['method' => 'GET', 'path' => '/analytics/inbox/conversations/test-id'], $this->calls[0]);
    }

    public function test_articles_generate(): void
    {
        $sq = $this->client();
        $sq->articles->generate([]);
        $this->assertSame(['method' => 'POST', 'path' => '/articles/generate'], $this->calls[0]);
    }

    public function test_articles_list(): void
    {
        $sq = $this->client();
        $sq->articles->list();
        $this->assertSame(['method' => 'GET', 'path' => '/articles'], $this->calls[0]);
    }

    public function test_articles_get(): void
    {
        $sq = $this->client();
        $sq->articles->get('test-id');
        $this->assertSame(['method' => 'GET', 'path' => '/articles/test-id'], $this->calls[0]);
    }

    public function test_articles_delete(): void
    {
        $sq = $this->client();
        $sq->articles->delete('test-id');
        $this->assertSame(['method' => 'DELETE', 'path' => '/articles/test-id'], $this->calls[0]);
    }

    public function test_audio_textToSpeech(): void
    {
        $sq = $this->client();
        $sq->audio->textToSpeech([]);
        $this->assertSame(['method' => 'POST', 'path' => '/audio/text-to-speech'], $this->calls[0]);
    }

    public function test_audio_speechToText(): void
    {
        $sq = $this->client();
        $sq->audio->speechToText([]);
        $this->assertSame(['method' => 'POST', 'path' => '/audio/speech-to-text'], $this->calls[0]);
    }

    public function test_audio_get(): void
    {
        $sq = $this->client();
        $sq->audio->get('test-id');
        $this->assertSame(['method' => 'GET', 'path' => '/audio/test-id'], $this->calls[0]);
    }

    public function test_automations_list(): void
    {
        $sq = $this->client();
        $sq->automations->list();
        $this->assertSame(['method' => 'GET', 'path' => '/automations'], $this->calls[0]);
    }

    public function test_automations_get(): void
    {
        $sq = $this->client();
        $sq->automations->get('test-id');
        $this->assertSame(['method' => 'GET', 'path' => '/automations/test-id'], $this->calls[0]);
    }

    public function test_automations_activate(): void
    {
        $sq = $this->client();
        $sq->automations->activate('test-id');
        $this->assertSame(['method' => 'POST', 'path' => '/automations/test-id/activate'], $this->calls[0]);
    }

    public function test_automations_deactivate(): void
    {
        $sq = $this->client();
        $sq->automations->deactivate('test-id');
        $this->assertSame(['method' => 'POST', 'path' => '/automations/test-id/deactivate'], $this->calls[0]);
    }

    public function test_automations_trigger(): void
    {
        $sq = $this->client();
        $sq->automations->trigger('test-id', []);
        $this->assertSame(['method' => 'POST', 'path' => '/automations/test-id/trigger'], $this->calls[0]);
    }

    public function test_automations_listRuns(): void
    {
        $sq = $this->client();
        $sq->automations->listRuns('test-id');
        $this->assertSame(['method' => 'GET', 'path' => '/automations/test-id/runs'], $this->calls[0]);
    }

    public function test_automations_getRun(): void
    {
        $sq = $this->client();
        $sq->automations->getRun('test-id', 'test-id');
        $this->assertSame(['method' => 'GET', 'path' => '/automations/test-id/runs/test-id'], $this->calls[0]);
    }

    public function test_chatbots_list(): void
    {
        $sq = $this->client();
        $sq->chatbots->list();
        $this->assertSame(['method' => 'GET', 'path' => '/chatbots'], $this->calls[0]);
    }

    public function test_chatbots_create(): void
    {
        $sq = $this->client();
        $sq->chatbots->create([]);
        $this->assertSame(['method' => 'POST', 'path' => '/chatbots'], $this->calls[0]);
    }

    public function test_chatbots_get(): void
    {
        $sq = $this->client();
        $sq->chatbots->get('test-id');
        $this->assertSame(['method' => 'GET', 'path' => '/chatbots/test-id'], $this->calls[0]);
    }

    public function test_chatbots_update(): void
    {
        $sq = $this->client();
        $sq->chatbots->update('test-id', []);
        $this->assertSame(['method' => 'PATCH', 'path' => '/chatbots/test-id'], $this->calls[0]);
    }

    public function test_chatbots_delete(): void
    {
        $sq = $this->client();
        $sq->chatbots->delete('test-id');
        $this->assertSame(['method' => 'DELETE', 'path' => '/chatbots/test-id'], $this->calls[0]);
    }

    public function test_chatbots_train(): void
    {
        $sq = $this->client();
        $sq->chatbots->train('test-id');
        $this->assertSame(['method' => 'POST', 'path' => '/chatbots/test-id/train'], $this->calls[0]);
    }

    public function test_chatbots_getTrainStatus(): void
    {
        $sq = $this->client();
        $sq->chatbots->getTrainStatus('test-id');
        $this->assertSame(['method' => 'GET', 'path' => '/chatbots/test-id/train-status'], $this->calls[0]);
    }

    public function test_chatbots_sendMessage(): void
    {
        $sq = $this->client();
        $sq->chatbots->sendMessage('test-id', []);
        $this->assertSame(['method' => 'POST', 'path' => '/chatbots/test-id/messages'], $this->calls[0]);
    }

    public function test_chatbots_listConversations(): void
    {
        $sq = $this->client();
        $sq->chatbots->listConversations('test-id');
        $this->assertSame(['method' => 'GET', 'path' => '/chatbots/test-id/conversations'], $this->calls[0]);
    }

    public function test_chatbots_getConversationMessages(): void
    {
        $sq = $this->client();
        $sq->chatbots->getConversationMessages('test-id', 'test-id');
        $this->assertSame(['method' => 'GET', 'path' => '/chatbots/test-id/conversations/test-id/messages'], $this->calls[0]);
    }

    public function test_comments_list(): void
    {
        $sq = $this->client();
        $sq->comments->list();
        $this->assertSame(['method' => 'GET', 'path' => '/social/comments'], $this->calls[0]);
    }

    public function test_comments_replyTo(): void
    {
        $sq = $this->client();
        $sq->comments->replyTo('test-id', []);
        $this->assertSame(['method' => 'POST', 'path' => '/social/comments/test-id/reply'], $this->calls[0]);
    }

    public function test_comments_hide(): void
    {
        $sq = $this->client();
        $sq->comments->hide('test-id');
        $this->assertSame(['method' => 'POST', 'path' => '/social/comments/test-id/hide'], $this->calls[0]);
    }

    public function test_comments_delete(): void
    {
        $sq = $this->client();
        $sq->comments->delete('test-id');
        $this->assertSame(['method' => 'DELETE', 'path' => '/social/comments/test-id'], $this->calls[0]);
    }

    public function test_comments_getPost(): void
    {
        $sq = $this->client();
        $sq->comments->getPost('test-id');
        $this->assertSame(['method' => 'GET', 'path' => '/social/comments/test-id'], $this->calls[0]);
    }

    public function test_content_rewrite(): void
    {
        $sq = $this->client();
        $sq->content->rewrite([]);
        $this->assertSame(['method' => 'POST', 'path' => '/content/rewrite'], $this->calls[0]);
    }

    public function test_content_generateCaption(): void
    {
        $sq = $this->client();
        $sq->content->generateCaption([]);
        $this->assertSame(['method' => 'POST', 'path' => '/content/caption'], $this->calls[0]);
    }

    public function test_cRM_deleteContact(): void
    {
        $sq = $this->client();
        $sq->cRM->deleteContact('test-id');
        $this->assertSame(['method' => 'DELETE', 'path' => '/contacts/test-id'], $this->calls[0]);
    }

    public function test_cRM_updateCustomField(): void
    {
        $sq = $this->client();
        $sq->cRM->updateCustomField('test-id', []);
        $this->assertSame(['method' => 'PATCH', 'path' => '/custom-fields/test-id'], $this->calls[0]);
    }

    public function test_cRM_bulkImportContacts(): void
    {
        $sq = $this->client();
        $sq->cRM->bulkImportContacts([]);
        $this->assertSame(['method' => 'POST', 'path' => '/contacts/bulk'], $this->calls[0]);
    }

    public function test_cRM_contactChannels(): void
    {
        $sq = $this->client();
        $sq->cRM->contactChannels('test-id');
        $this->assertSame(['method' => 'GET', 'path' => '/contacts/test-id/channels'], $this->calls[0]);
    }

    public function test_contacts_list(): void
    {
        $sq = $this->client();
        $sq->contacts->list();
        $this->assertSame(['method' => 'GET', 'path' => '/contacts'], $this->calls[0]);
    }

    public function test_contacts_create(): void
    {
        $sq = $this->client();
        $sq->contacts->create([]);
        $this->assertSame(['method' => 'POST', 'path' => '/contacts'], $this->calls[0]);
    }

    public function test_contacts_get(): void
    {
        $sq = $this->client();
        $sq->contacts->get('test-id');
        $this->assertSame(['method' => 'GET', 'path' => '/contacts/test-id'], $this->calls[0]);
    }

    public function test_contacts_update(): void
    {
        $sq = $this->client();
        $sq->contacts->update('test-id', []);
        $this->assertSame(['method' => 'PATCH', 'path' => '/contacts/test-id'], $this->calls[0]);
    }

    public function test_contacts_addTags(): void
    {
        $sq = $this->client();
        $sq->contacts->addTags('test-id', []);
        $this->assertSame(['method' => 'POST', 'path' => '/contacts/test-id/tags'], $this->calls[0]);
    }

    public function test_contacts_removeTags(): void
    {
        $sq = $this->client();
        $sq->contacts->removeTags('test-id', []);
        $this->assertSame(['method' => 'DELETE', 'path' => '/contacts/test-id/tags'], $this->calls[0]);
    }

    public function test_contacts_listNotes(): void
    {
        $sq = $this->client();
        $sq->contacts->listNotes('test-id');
        $this->assertSame(['method' => 'GET', 'path' => '/contacts/test-id/notes'], $this->calls[0]);
    }

    public function test_contacts_addNote(): void
    {
        $sq = $this->client();
        $sq->contacts->addNote('test-id', []);
        $this->assertSame(['method' => 'POST', 'path' => '/contacts/test-id/notes'], $this->calls[0]);
    }

    public function test_contacts_enroll(): void
    {
        $sq = $this->client();
        $sq->contacts->enroll('test-id', []);
        $this->assertSame(['method' => 'POST', 'path' => '/contacts/test-id/enroll'], $this->calls[0]);
    }

    public function test_contacts_addMessage(): void
    {
        $sq = $this->client();
        $sq->contacts->addMessage('test-id', []);
        $this->assertSame(['method' => 'POST', 'path' => '/contacts/test-id/messages'], $this->calls[0]);
    }

    public function test_contacts_setField(): void
    {
        $sq = $this->client();
        $sq->contacts->setField('test-id', 'test-id', []);
        $this->assertSame(['method' => 'PUT', 'path' => '/contacts/test-id/fields/test-id'], $this->calls[0]);
    }

    public function test_contacts_clearField(): void
    {
        $sq = $this->client();
        $sq->contacts->clearField('test-id', 'test-id');
        $this->assertSame(['method' => 'DELETE', 'path' => '/contacts/test-id/fields/test-id'], $this->calls[0]);
    }

    public function test_customFields_list(): void
    {
        $sq = $this->client();
        $sq->customFields->list();
        $this->assertSame(['method' => 'GET', 'path' => '/custom-fields'], $this->calls[0]);
    }

    public function test_customFields_create(): void
    {
        $sq = $this->client();
        $sq->customFields->create([]);
        $this->assertSame(['method' => 'POST', 'path' => '/custom-fields'], $this->calls[0]);
    }

    public function test_customFields_delete(): void
    {
        $sq = $this->client();
        $sq->customFields->delete('test-id');
        $this->assertSame(['method' => 'DELETE', 'path' => '/custom-fields/test-id'], $this->calls[0]);
    }

    public function test_opportunities_listPipelines(): void
    {
        $sq = $this->client();
        $sq->opportunities->listPipelines();
        $this->assertSame(['method' => 'GET', 'path' => '/pipelines'], $this->calls[0]);
    }

    public function test_opportunities_createPipeline(): void
    {
        $sq = $this->client();
        $sq->opportunities->createPipeline([]);
        $this->assertSame(['method' => 'POST', 'path' => '/pipelines'], $this->calls[0]);
    }

    public function test_opportunities_list(): void
    {
        $sq = $this->client();
        $sq->opportunities->list();
        $this->assertSame(['method' => 'GET', 'path' => '/opportunities'], $this->calls[0]);
    }

    public function test_opportunities_create(): void
    {
        $sq = $this->client();
        $sq->opportunities->create([]);
        $this->assertSame(['method' => 'POST', 'path' => '/opportunities'], $this->calls[0]);
    }

    public function test_opportunities_get(): void
    {
        $sq = $this->client();
        $sq->opportunities->get('test-id');
        $this->assertSame(['method' => 'GET', 'path' => '/opportunities/test-id'], $this->calls[0]);
    }

    public function test_opportunities_update(): void
    {
        $sq = $this->client();
        $sq->opportunities->update('test-id', []);
        $this->assertSame(['method' => 'PATCH', 'path' => '/opportunities/test-id'], $this->calls[0]);
    }

    public function test_opportunities_delete(): void
    {
        $sq = $this->client();
        $sq->opportunities->delete('test-id');
        $this->assertSame(['method' => 'DELETE', 'path' => '/opportunities/test-id'], $this->calls[0]);
    }

    public function test_opportunities_updateStatus(): void
    {
        $sq = $this->client();
        $sq->opportunities->updateStatus('test-id', []);
        $this->assertSame(['method' => 'POST', 'path' => '/opportunities/test-id/status'], $this->calls[0]);
    }

    public function test_messages_listConversations(): void
    {
        $sq = $this->client();
        $sq->messages->listConversations();
        $this->assertSame(['method' => 'GET', 'path' => '/social/conversations'], $this->calls[0]);
    }

    public function test_messages_list(): void
    {
        $sq = $this->client();
        $sq->messages->list('test-id');
        $this->assertSame(['method' => 'GET', 'path' => '/social/conversations/test-id/messages'], $this->calls[0]);
    }

    public function test_messages_send(): void
    {
        $sq = $this->client();
        $sq->messages->send('test-id', []);
        $this->assertSame(['method' => 'POST', 'path' => '/social/conversations/test-id/messages'], $this->calls[0]);
    }

    public function test_messages_markConversationRead(): void
    {
        $sq = $this->client();
        $sq->messages->markConversationRead('test-id');
        $this->assertSame(['method' => 'POST', 'path' => '/social/conversations/test-id/read'], $this->calls[0]);
    }

    public function test_images_generate(): void
    {
        $sq = $this->client();
        $sq->images->generate([]);
        $this->assertSame(['method' => 'POST', 'path' => '/images/generate'], $this->calls[0]);
    }

    public function test_images_list(): void
    {
        $sq = $this->client();
        $sq->images->list();
        $this->assertSame(['method' => 'GET', 'path' => '/images'], $this->calls[0]);
    }

    public function test_images_get(): void
    {
        $sq = $this->client();
        $sq->images->get('test-id');
        $this->assertSame(['method' => 'GET', 'path' => '/images/test-id'], $this->calls[0]);
    }

    public function test_images_delete(): void
    {
        $sq = $this->client();
        $sq->images->delete('test-id');
        $this->assertSame(['method' => 'DELETE', 'path' => '/images/test-id'], $this->calls[0]);
    }

    public function test_jobs_list(): void
    {
        $sq = $this->client();
        $sq->jobs->list();
        $this->assertSame(['method' => 'GET', 'path' => '/jobs'], $this->calls[0]);
    }

    public function test_jobs_get(): void
    {
        $sq = $this->client();
        $sq->jobs->get('test-id');
        $this->assertSame(['method' => 'GET', 'path' => '/jobs/test-id'], $this->calls[0]);
    }

    public function test_jobs_cancel(): void
    {
        $sq = $this->client();
        $sq->jobs->cancel('test-id', []);
        $this->assertSame(['method' => 'POST', 'path' => '/jobs/test-id/cancel'], $this->calls[0]);
    }

    public function test_media_list(): void
    {
        $sq = $this->client();
        $sq->media->list();
        $this->assertSame(['method' => 'GET', 'path' => '/media'], $this->calls[0]);
    }

    public function test_media_get(): void
    {
        $sq = $this->client();
        $sq->media->get('test-id');
        $this->assertSame(['method' => 'GET', 'path' => '/media/test-id'], $this->calls[0]);
    }

    public function test_media_delete(): void
    {
        $sq = $this->client();
        $sq->media->delete('test-id');
        $this->assertSame(['method' => 'DELETE', 'path' => '/media/test-id'], $this->calls[0]);
    }

    public function test_media_getUploadUrl(): void
    {
        $sq = $this->client();
        $sq->media->getUploadUrl([]);
        $this->assertSame(['method' => 'POST', 'path' => '/media/upload-url'], $this->calls[0]);
    }

    public function test_media_uploadDirect(): void
    {
        $sq = $this->client();
        $sq->media->uploadDirect([]);
        $this->assertSame(['method' => 'POST', 'path' => '/media/upload-direct'], $this->calls[0]);
    }

    public function test_presentations_generate(): void
    {
        $sq = $this->client();
        $sq->presentations->generate([]);
        $this->assertSame(['method' => 'POST', 'path' => '/presentations/generate'], $this->calls[0]);
    }

    public function test_presentations_list(): void
    {
        $sq = $this->client();
        $sq->presentations->list();
        $this->assertSame(['method' => 'GET', 'path' => '/presentations'], $this->calls[0]);
    }

    public function test_presentations_get(): void
    {
        $sq = $this->client();
        $sq->presentations->get('test-id');
        $this->assertSame(['method' => 'GET', 'path' => '/presentations/test-id'], $this->calls[0]);
    }

    public function test_presentations_delete(): void
    {
        $sq = $this->client();
        $sq->presentations->delete('test-id');
        $this->assertSame(['method' => 'DELETE', 'path' => '/presentations/test-id'], $this->calls[0]);
    }

    public function test_profiles_list(): void
    {
        $sq = $this->client();
        $sq->profiles->list();
        $this->assertSame(['method' => 'GET', 'path' => '/profiles'], $this->calls[0]);
    }

    public function test_profiles_create(): void
    {
        $sq = $this->client();
        $sq->profiles->create([]);
        $this->assertSame(['method' => 'POST', 'path' => '/profiles'], $this->calls[0]);
    }

    public function test_profiles_get(): void
    {
        $sq = $this->client();
        $sq->profiles->get('test-id');
        $this->assertSame(['method' => 'GET', 'path' => '/profiles/test-id'], $this->calls[0]);
    }

    public function test_profiles_update(): void
    {
        $sq = $this->client();
        $sq->profiles->update('test-id', []);
        $this->assertSame(['method' => 'PATCH', 'path' => '/profiles/test-id'], $this->calls[0]);
    }

    public function test_profiles_delete(): void
    {
        $sq = $this->client();
        $sq->profiles->delete('test-id', []);
        $this->assertSame(['method' => 'DELETE', 'path' => '/profiles/test-id'], $this->calls[0]);
    }

    public function test_profiles_listAccounts(): void
    {
        $sq = $this->client();
        $sq->profiles->listAccounts('test-id');
        $this->assertSame(['method' => 'GET', 'path' => '/profiles/test-id/accounts'], $this->calls[0]);
    }

    public function test_profiles_pause(): void
    {
        $sq = $this->client();
        $sq->profiles->pause('test-id');
        $this->assertSame(['method' => 'POST', 'path' => '/profiles/test-id/pause'], $this->calls[0]);
    }

    public function test_profiles_resume(): void
    {
        $sq = $this->client();
        $sq->profiles->resume('test-id');
        $this->assertSame(['method' => 'POST', 'path' => '/profiles/test-id/resume'], $this->calls[0]);
    }

    public function test_profiles_createConnectLink(): void
    {
        $sq = $this->client();
        $sq->profiles->createConnectLink('test-id', []);
        $this->assertSame(['method' => 'POST', 'path' => '/profiles/test-id/connect-link'], $this->calls[0]);
    }

    public function test_profiles_createConnectUrl(): void
    {
        $sq = $this->client();
        $sq->profiles->createConnectUrl('test-id', 'test-id', []);
        $this->assertSame(['method' => 'POST', 'path' => '/profiles/test-id/connect/test-id'], $this->calls[0]);
    }

    public function test_profiles_getAccountBilling(): void
    {
        $sq = $this->client();
        $sq->profiles->getAccountBilling();
        $this->assertSame(['method' => 'GET', 'path' => '/me/account-billing'], $this->calls[0]);
    }

    public function test_reviews_list(): void
    {
        $sq = $this->client();
        $sq->reviews->list();
        $this->assertSame(['method' => 'GET', 'path' => '/reviews'], $this->calls[0]);
    }

    public function test_reviews_replyTo(): void
    {
        $sq = $this->client();
        $sq->reviews->replyTo('test-id', []);
        $this->assertSame(['method' => 'POST', 'path' => '/reviews/test-id/reply'], $this->calls[0]);
    }

    public function test_reviews_deleteReply(): void
    {
        $sq = $this->client();
        $sq->reviews->deleteReply('test-id');
        $this->assertSame(['method' => 'DELETE', 'path' => '/reviews/test-id/reply'], $this->calls[0]);
    }

    public function test_reviews_sync(): void
    {
        $sq = $this->client();
        $sq->reviews->sync([]);
        $this->assertSame(['method' => 'POST', 'path' => '/reviews/sync'], $this->calls[0]);
    }

    public function test_seo_keywordResearch(): void
    {
        $sq = $this->client();
        $sq->seo->keywordResearch([]);
        $this->assertSame(['method' => 'POST', 'path' => '/seo/keyword-research'], $this->calls[0]);
    }

    public function test_seo_serp(): void
    {
        $sq = $this->client();
        $sq->seo->serp([]);
        $this->assertSame(['method' => 'POST', 'path' => '/seo/serp'], $this->calls[0]);
    }

    public function test_seo_keywordDifficulty(): void
    {
        $sq = $this->client();
        $sq->seo->keywordDifficulty([]);
        $this->assertSame(['method' => 'POST', 'path' => '/seo/keyword-difficulty'], $this->calls[0]);
    }

    public function test_seo_rankedKeywords(): void
    {
        $sq = $this->client();
        $sq->seo->rankedKeywords([]);
        $this->assertSame(['method' => 'POST', 'path' => '/seo/ranked-keywords'], $this->calls[0]);
    }

    public function test_seo_domainOverview(): void
    {
        $sq = $this->client();
        $sq->seo->domainOverview([]);
        $this->assertSame(['method' => 'POST', 'path' => '/seo/domain-overview'], $this->calls[0]);
    }

    public function test_seo_competitors(): void
    {
        $sq = $this->client();
        $sq->seo->competitors([]);
        $this->assertSame(['method' => 'POST', 'path' => '/seo/competitors'], $this->calls[0]);
    }

    public function test_seo_backlinksSummary(): void
    {
        $sq = $this->client();
        $sq->seo->backlinksSummary([]);
        $this->assertSame(['method' => 'POST', 'path' => '/seo/backlinks-summary'], $this->calls[0]);
    }

    public function test_seo_audit(): void
    {
        $sq = $this->client();
        $sq->seo->audit([]);
        $this->assertSame(['method' => 'POST', 'path' => '/seo/audit'], $this->calls[0]);
    }

    public function test_seo_backlinkProspects(): void
    {
        $sq = $this->client();
        $sq->seo->backlinkProspects([]);
        $this->assertSame(['method' => 'POST', 'path' => '/seo/backlink-prospects'], $this->calls[0]);
    }

    public function test_seo_referringDomains(): void
    {
        $sq = $this->client();
        $sq->seo->referringDomains([]);
        $this->assertSame(['method' => 'POST', 'path' => '/seo/referring-domains'], $this->calls[0]);
    }

    public function test_seo_backlinkAnchors(): void
    {
        $sq = $this->client();
        $sq->seo->backlinkAnchors([]);
        $this->assertSame(['method' => 'POST', 'path' => '/seo/backlink-anchors'], $this->calls[0]);
    }

    public function test_seo_spamScore(): void
    {
        $sq = $this->client();
        $sq->seo->spamScore([]);
        $this->assertSame(['method' => 'POST', 'path' => '/seo/spam-score'], $this->calls[0]);
    }

    public function test_seo_rankHistory(): void
    {
        $sq = $this->client();
        $sq->seo->rankHistory([]);
        $this->assertSame(['method' => 'POST', 'path' => '/seo/rank-history'], $this->calls[0]);
    }

    public function test_seo_siteAudit(): void
    {
        $sq = $this->client();
        $sq->seo->siteAudit([]);
        $this->assertSame(['method' => 'POST', 'path' => '/seo/site-audit'], $this->calls[0]);
    }

    public function test_seo_brandLookup(): void
    {
        $sq = $this->client();
        $sq->seo->brandLookup([]);
        $this->assertSame(['method' => 'POST', 'path' => '/seo/brand-lookup'], $this->calls[0]);
    }

    public function test_seo_promptExplorer(): void
    {
        $sq = $this->client();
        $sq->seo->promptExplorer([]);
        $this->assertSame(['method' => 'POST', 'path' => '/seo/prompt-explorer'], $this->calls[0]);
    }

    public function test_seo_aiAudit(): void
    {
        $sq = $this->client();
        $sq->seo->aiAudit([]);
        $this->assertSame(['method' => 'POST', 'path' => '/seo/ai-audit'], $this->calls[0]);
    }

    public function test_shorts_generate(): void
    {
        $sq = $this->client();
        $sq->shorts->generate([]);
        $this->assertSame(['method' => 'POST', 'path' => '/shorts/generate'], $this->calls[0]);
    }

    public function test_shorts_list(): void
    {
        $sq = $this->client();
        $sq->shorts->list();
        $this->assertSame(['method' => 'GET', 'path' => '/shorts'], $this->calls[0]);
    }

    public function test_shorts_get(): void
    {
        $sq = $this->client();
        $sq->shorts->get('test-id');
        $this->assertSame(['method' => 'GET', 'path' => '/shorts/test-id'], $this->calls[0]);
    }

    public function test_social_listAccounts(): void
    {
        $sq = $this->client();
        $sq->social->listAccounts();
        $this->assertSame(['method' => 'GET', 'path' => '/social/accounts'], $this->calls[0]);
    }

    public function test_social_listPosts(): void
    {
        $sq = $this->client();
        $sq->social->listPosts();
        $this->assertSame(['method' => 'GET', 'path' => '/social/posts'], $this->calls[0]);
    }

    public function test_social_createPost(): void
    {
        $sq = $this->client();
        $sq->social->createPost([]);
        $this->assertSame(['method' => 'POST', 'path' => '/social/posts'], $this->calls[0]);
    }

    public function test_social_schedulePost(): void
    {
        $sq = $this->client();
        $sq->social->schedulePost([]);
        $this->assertSame(['method' => 'POST', 'path' => '/social/posts/schedule'], $this->calls[0]);
    }

    public function test_social_getPost(): void
    {
        $sq = $this->client();
        $sq->social->getPost('test-id');
        $this->assertSame(['method' => 'GET', 'path' => '/social/posts/test-id'], $this->calls[0]);
    }

    public function test_social_updatePost(): void
    {
        $sq = $this->client();
        $sq->social->updatePost('test-id', []);
        $this->assertSame(['method' => 'PATCH', 'path' => '/social/posts/test-id'], $this->calls[0]);
    }

    public function test_social_deletePost(): void
    {
        $sq = $this->client();
        $sq->social->deletePost('test-id');
        $this->assertSame(['method' => 'DELETE', 'path' => '/social/posts/test-id'], $this->calls[0]);
    }

    public function test_social_updateAccount(): void
    {
        $sq = $this->client();
        $sq->social->updateAccount('test-id', []);
        $this->assertSame(['method' => 'PATCH', 'path' => '/social/accounts/test-id'], $this->calls[0]);
    }

    public function test_social_disconnectAccount(): void
    {
        $sq = $this->client();
        $sq->social->disconnectAccount('test-id');
        $this->assertSame(['method' => 'DELETE', 'path' => '/social/accounts/test-id'], $this->calls[0]);
    }

    public function test_social_getAccountHealth(): void
    {
        $sq = $this->client();
        $sq->social->getAccountHealth('test-id');
        $this->assertSame(['method' => 'GET', 'path' => '/social/accounts/test-id/health'], $this->calls[0]);
    }

    public function test_social_getAccountReconnectUrl(): void
    {
        $sq = $this->client();
        $sq->social->getAccountReconnectUrl('test-id');
        $this->assertSame(['method' => 'GET', 'path' => '/social/accounts/test-id/reconnect-url'], $this->calls[0]);
    }

    public function test_social_pauseAccount(): void
    {
        $sq = $this->client();
        $sq->social->pauseAccount('test-id');
        $this->assertSame(['method' => 'POST', 'path' => '/social/accounts/test-id/pause'], $this->calls[0]);
    }

    public function test_social_resumeAccount(): void
    {
        $sq = $this->client();
        $sq->social->resumeAccount('test-id');
        $this->assertSame(['method' => 'POST', 'path' => '/social/accounts/test-id/resume'], $this->calls[0]);
    }

    public function test_social_retryPost(): void
    {
        $sq = $this->client();
        $sq->social->retryPost('test-id', []);
        $this->assertSame(['method' => 'POST', 'path' => '/social/posts/test-id/retry'], $this->calls[0]);
    }

    public function test_social_connectAccountStatus(): void
    {
        $sq = $this->client();
        $sq->social->connectAccountStatus('test-id');
        $this->assertSame(['method' => 'GET', 'path' => '/social/connect/test-id'], $this->calls[0]);
    }

    public function test_social_connectAccount(): void
    {
        $sq = $this->client();
        $sq->social->connectAccount('test-id', []);
        $this->assertSame(['method' => 'POST', 'path' => '/social/connect/test-id'], $this->calls[0]);
    }

    public function test_social_listQueues(): void
    {
        $sq = $this->client();
        $sq->social->listQueues();
        $this->assertSame(['method' => 'GET', 'path' => '/social/queues'], $this->calls[0]);
    }

    public function test_social_createQueue(): void
    {
        $sq = $this->client();
        $sq->social->createQueue([]);
        $this->assertSame(['method' => 'POST', 'path' => '/social/queues'], $this->calls[0]);
    }

    public function test_social_getQueue(): void
    {
        $sq = $this->client();
        $sq->social->getQueue('test-id');
        $this->assertSame(['method' => 'GET', 'path' => '/social/queues/test-id'], $this->calls[0]);
    }

    public function test_social_updateQueue(): void
    {
        $sq = $this->client();
        $sq->social->updateQueue('test-id', []);
        $this->assertSame(['method' => 'PUT', 'path' => '/social/queues/test-id'], $this->calls[0]);
    }

    public function test_social_deleteQueue(): void
    {
        $sq = $this->client();
        $sq->social->deleteQueue('test-id');
        $this->assertSame(['method' => 'DELETE', 'path' => '/social/queues/test-id'], $this->calls[0]);
    }

    public function test_social_getQueueNextSlot(): void
    {
        $sq = $this->client();
        $sq->social->getQueueNextSlot('test-id');
        $this->assertSame(['method' => 'GET', 'path' => '/social/queues/test-id/next-slot'], $this->calls[0]);
    }

    public function test_social_previewQueueSlots(): void
    {
        $sq = $this->client();
        $sq->social->previewQueueSlots('test-id');
        $this->assertSame(['method' => 'GET', 'path' => '/social/queues/test-id/preview'], $this->calls[0]);
    }

    public function test_social_unpublishPost(): void
    {
        $sq = $this->client();
        $sq->social->unpublishPost('test-id', []);
        $this->assertSame(['method' => 'POST', 'path' => '/social/posts/test-id/unpublish'], $this->calls[0]);
    }

    public function test_social_validatePost(): void
    {
        $sq = $this->client();
        $sq->social->validatePost([]);
        $this->assertSame(['method' => 'POST', 'path' => '/social/validate/post'], $this->calls[0]);
    }

    public function test_social_validateMedia(): void
    {
        $sq = $this->client();
        $sq->social->validateMedia([]);
        $this->assertSame(['method' => 'POST', 'path' => '/social/validate/media'], $this->calls[0]);
    }

    public function test_social_stopPostRecycle(): void
    {
        $sq = $this->client();
        $sq->social->stopPostRecycle('test-id');
        $this->assertSame(['method' => 'DELETE', 'path' => '/social/posts/test-id/recycle'], $this->calls[0]);
    }

    public function test_social_bulkSchedulePosts(): void
    {
        $sq = $this->client();
        $sq->social->bulkSchedulePosts([]);
        $this->assertSame(['method' => 'POST', 'path' => '/social/posts/bulk'], $this->calls[0]);
    }

    public function test_social_validateBulkBatch(): void
    {
        $sq = $this->client();
        $sq->social->validateBulkBatch([]);
        $this->assertSame(['method' => 'POST', 'path' => '/social/posts/bulk/validate'], $this->calls[0]);
    }

    public function test_social_bulkAccountHealth(): void
    {
        $sq = $this->client();
        $sq->social->bulkAccountHealth();
        $this->assertSame(['method' => 'GET', 'path' => '/social/accounts/health'], $this->calls[0]);
    }

    public function test_social_accountFollowerStats(): void
    {
        $sq = $this->client();
        $sq->social->accountFollowerStats();
        $this->assertSame(['method' => 'GET', 'path' => '/social/accounts/follower-stats'], $this->calls[0]);
    }

    public function test_social_tiktokCreatorInfo(): void
    {
        $sq = $this->client();
        $sq->social->tiktokCreatorInfo('test-id');
        $this->assertSame(['method' => 'GET', 'path' => '/social/accounts/test-id/tiktok/creator-info'], $this->calls[0]);
    }

    public function test_social_moveAccount(): void
    {
        $sq = $this->client();
        $sq->social->moveAccount('test-id', []);
        $this->assertSame(['method' => 'POST', 'path' => '/social/accounts/test-id/move'], $this->calls[0]);
    }

    public function test_social_listAccountGroups(): void
    {
        $sq = $this->client();
        $sq->social->listAccountGroups();
        $this->assertSame(['method' => 'GET', 'path' => '/social/account-groups'], $this->calls[0]);
    }

    public function test_social_createAccountGroup(): void
    {
        $sq = $this->client();
        $sq->social->createAccountGroup([]);
        $this->assertSame(['method' => 'POST', 'path' => '/social/account-groups'], $this->calls[0]);
    }

    public function test_social_getAccountGroup(): void
    {
        $sq = $this->client();
        $sq->social->getAccountGroup('test-id');
        $this->assertSame(['method' => 'GET', 'path' => '/social/account-groups/test-id'], $this->calls[0]);
    }

    public function test_social_updateAccountGroup(): void
    {
        $sq = $this->client();
        $sq->social->updateAccountGroup('test-id', []);
        $this->assertSame(['method' => 'PUT', 'path' => '/social/account-groups/test-id'], $this->calls[0]);
    }

    public function test_social_deleteAccountGroup(): void
    {
        $sq = $this->client();
        $sq->social->deleteAccountGroup('test-id');
        $this->assertSame(['method' => 'DELETE', 'path' => '/social/account-groups/test-id'], $this->calls[0]);
    }

    public function test_social_getConversation(): void
    {
        $sq = $this->client();
        $sq->social->getConversation('test-id');
        $this->assertSame(['method' => 'GET', 'path' => '/social/conversations/test-id'], $this->calls[0]);
    }

    public function test_social_updateConversation(): void
    {
        $sq = $this->client();
        $sq->social->updateConversation('test-id', []);
        $this->assertSame(['method' => 'PATCH', 'path' => '/social/conversations/test-id'], $this->calls[0]);
    }

    public function test_social_searchConversations(): void
    {
        $sq = $this->client();
        $sq->social->searchConversations();
        $this->assertSame(['method' => 'GET', 'path' => '/social/conversations/search'], $this->calls[0]);
    }

    public function test_social_pinterestBoards(): void
    {
        $sq = $this->client();
        $sq->social->pinterestBoards('test-id');
        $this->assertSame(['method' => 'GET', 'path' => '/social/accounts/test-id/pinterest/boards'], $this->calls[0]);
    }

    public function test_social_youtubePlaylists(): void
    {
        $sq = $this->client();
        $sq->social->youtubePlaylists('test-id');
        $this->assertSame(['method' => 'GET', 'path' => '/social/accounts/test-id/youtube/playlists'], $this->calls[0]);
    }

    public function test_social_instagramPublishingLimit(): void
    {
        $sq = $this->client();
        $sq->social->instagramPublishingLimit('test-id');
        $this->assertSame(['method' => 'GET', 'path' => '/social/accounts/test-id/instagram/publishing-limit'], $this->calls[0]);
    }

    public function test_social_gmbPerformance(): void
    {
        $sq = $this->client();
        $sq->social->gmbPerformance('test-id');
        $this->assertSame(['method' => 'GET', 'path' => '/social/accounts/test-id/gmb/performance'], $this->calls[0]);
    }

    public function test_social_gmbSearchKeywords(): void
    {
        $sq = $this->client();
        $sq->social->gmbSearchKeywords('test-id');
        $this->assertSame(['method' => 'GET', 'path' => '/social/accounts/test-id/gmb/search-keywords'], $this->calls[0]);
    }

    public function test_social_redditSearch(): void
    {
        $sq = $this->client();
        $sq->social->redditSearch('test-id');
        $this->assertSame(['method' => 'GET', 'path' => '/social/accounts/test-id/reddit/search'], $this->calls[0]);
    }

    public function test_social_redditFeed(): void
    {
        $sq = $this->client();
        $sq->social->redditFeed('test-id');
        $this->assertSame(['method' => 'GET', 'path' => '/social/accounts/test-id/reddit/feed'], $this->calls[0]);
    }

    public function test_social_redditSubreddits(): void
    {
        $sq = $this->client();
        $sq->social->redditSubreddits('test-id');
        $this->assertSame(['method' => 'GET', 'path' => '/social/accounts/test-id/reddit/subreddits'], $this->calls[0]);
    }

    public function test_social_redditSubredditRules(): void
    {
        $sq = $this->client();
        $sq->social->redditSubredditRules('test-id', 'test-id');
        $this->assertSame(['method' => 'GET', 'path' => '/social/accounts/test-id/reddit/subreddits/test-id/rules'], $this->calls[0]);
    }

    public function test_social_instagramStories(): void
    {
        $sq = $this->client();
        $sq->social->instagramStories('test-id');
        $this->assertSame(['method' => 'GET', 'path' => '/social/accounts/test-id/instagram/stories'], $this->calls[0]);
    }

    public function test_social_facebookPostReactions(): void
    {
        $sq = $this->client();
        $sq->social->facebookPostReactions('test-id');
        $this->assertSame(['method' => 'GET', 'path' => '/social/accounts/test-id/facebook/post-reactions'], $this->calls[0]);
    }

    public function test_social_instagramStoryInsights(): void
    {
        $sq = $this->client();
        $sq->social->instagramStoryInsights('test-id', 'test-id');
        $this->assertSame(['method' => 'GET', 'path' => '/social/accounts/test-id/instagram/stories/test-id/insights'], $this->calls[0]);
    }

    public function test_social_xRetweet(): void
    {
        $sq = $this->client();
        $sq->social->xRetweet('test-id', []);
        $this->assertSame(['method' => 'POST', 'path' => '/social/accounts/test-id/x/retweets'], $this->calls[0]);
    }

    public function test_social_xUnretweet(): void
    {
        $sq = $this->client();
        $sq->social->xUnretweet('test-id', 'test-id');
        $this->assertSame(['method' => 'DELETE', 'path' => '/social/accounts/test-id/x/retweets/test-id'], $this->calls[0]);
    }

    public function test_social_editPublishedPost(): void
    {
        $sq = $this->client();
        $sq->social->editPublishedPost('test-id', []);
        $this->assertSame(['method' => 'POST', 'path' => '/social/posts/test-id/edit'], $this->calls[0]);
    }

    public function test_social_updatePostMetadata(): void
    {
        $sq = $this->client();
        $sq->social->updatePostMetadata('test-id', []);
        $this->assertSame(['method' => 'POST', 'path' => '/social/posts/test-id/update-metadata'], $this->calls[0]);
    }

    public function test_social_syncExternalPosts(): void
    {
        $sq = $this->client();
        $sq->social->syncExternalPosts([]);
        $this->assertSame(['method' => 'POST', 'path' => '/social/posts/sync-external'], $this->calls[0]);
    }

    public function test_social_accountInsights(): void
    {
        $sq = $this->client();
        $sq->social->accountInsights('test-id');
        $this->assertSame(['method' => 'GET', 'path' => '/social/accounts/test-id/insights'], $this->calls[0]);
    }

    public function test_social_gmbLocations(): void
    {
        $sq = $this->client();
        $sq->social->gmbLocations('test-id');
        $this->assertSame(['method' => 'GET', 'path' => '/social/accounts/test-id/gmb/locations'], $this->calls[0]);
    }

    public function test_social_gmbLocation(): void
    {
        $sq = $this->client();
        $sq->social->gmbLocation('test-id');
        $this->assertSame(['method' => 'GET', 'path' => '/social/accounts/test-id/gmb/location'], $this->calls[0]);
    }

    public function test_social_gmbUpdateLocation(): void
    {
        $sq = $this->client();
        $sq->social->gmbUpdateLocation('test-id', []);
        $this->assertSame(['method' => 'PATCH', 'path' => '/social/accounts/test-id/gmb/location'], $this->calls[0]);
    }

    public function test_social_gmbAttributes(): void
    {
        $sq = $this->client();
        $sq->social->gmbAttributes('test-id');
        $this->assertSame(['method' => 'GET', 'path' => '/social/accounts/test-id/gmb/attributes'], $this->calls[0]);
    }

    public function test_social_gmbUpdateAttributes(): void
    {
        $sq = $this->client();
        $sq->social->gmbUpdateAttributes('test-id', []);
        $this->assertSame(['method' => 'PUT', 'path' => '/social/accounts/test-id/gmb/attributes'], $this->calls[0]);
    }

    public function test_social_gmbAttributeMetadata(): void
    {
        $sq = $this->client();
        $sq->social->gmbAttributeMetadata('test-id');
        $this->assertSame(['method' => 'GET', 'path' => '/social/accounts/test-id/gmb/attributes/metadata'], $this->calls[0]);
    }

    public function test_social_gmbMedia(): void
    {
        $sq = $this->client();
        $sq->social->gmbMedia('test-id');
        $this->assertSame(['method' => 'GET', 'path' => '/social/accounts/test-id/gmb/media'], $this->calls[0]);
    }

    public function test_social_gmbCreateMedia(): void
    {
        $sq = $this->client();
        $sq->social->gmbCreateMedia('test-id', []);
        $this->assertSame(['method' => 'POST', 'path' => '/social/accounts/test-id/gmb/media'], $this->calls[0]);
    }

    public function test_social_gmbDeleteMedia(): void
    {
        $sq = $this->client();
        $sq->social->gmbDeleteMedia('test-id', []);
        $this->assertSame(['method' => 'DELETE', 'path' => '/social/accounts/test-id/gmb/media'], $this->calls[0]);
    }

    public function test_social_gmbFoodMenus(): void
    {
        $sq = $this->client();
        $sq->social->gmbFoodMenus('test-id');
        $this->assertSame(['method' => 'GET', 'path' => '/social/accounts/test-id/gmb/food-menus'], $this->calls[0]);
    }

    public function test_social_gmbUpdateFoodMenus(): void
    {
        $sq = $this->client();
        $sq->social->gmbUpdateFoodMenus('test-id', []);
        $this->assertSame(['method' => 'PUT', 'path' => '/social/accounts/test-id/gmb/food-menus'], $this->calls[0]);
    }

    public function test_social_gmbPlaceActions(): void
    {
        $sq = $this->client();
        $sq->social->gmbPlaceActions('test-id');
        $this->assertSame(['method' => 'GET', 'path' => '/social/accounts/test-id/gmb/place-actions'], $this->calls[0]);
    }

    public function test_social_gmbCreatePlaceAction(): void
    {
        $sq = $this->client();
        $sq->social->gmbCreatePlaceAction('test-id', []);
        $this->assertSame(['method' => 'POST', 'path' => '/social/accounts/test-id/gmb/place-actions'], $this->calls[0]);
    }

    public function test_social_gmbUpdatePlaceAction(): void
    {
        $sq = $this->client();
        $sq->social->gmbUpdatePlaceAction('test-id', []);
        $this->assertSame(['method' => 'PATCH', 'path' => '/social/accounts/test-id/gmb/place-actions'], $this->calls[0]);
    }

    public function test_social_gmbDeletePlaceAction(): void
    {
        $sq = $this->client();
        $sq->social->gmbDeletePlaceAction('test-id', []);
        $this->assertSame(['method' => 'DELETE', 'path' => '/social/accounts/test-id/gmb/place-actions'], $this->calls[0]);
    }

    public function test_social_gmbVerifications(): void
    {
        $sq = $this->client();
        $sq->social->gmbVerifications('test-id');
        $this->assertSame(['method' => 'GET', 'path' => '/social/accounts/test-id/gmb/verifications'], $this->calls[0]);
    }

    public function test_social_gmbVerificationOptions(): void
    {
        $sq = $this->client();
        $sq->social->gmbVerificationOptions('test-id', []);
        $this->assertSame(['method' => 'POST', 'path' => '/social/accounts/test-id/gmb/verifications/options'], $this->calls[0]);
    }

    public function test_social_redditSubredditInfo(): void
    {
        $sq = $this->client();
        $sq->social->redditSubredditInfo('test-id', 'test-id');
        $this->assertSame(['method' => 'GET', 'path' => '/social/accounts/test-id/reddit/subreddits/test-id'], $this->calls[0]);
    }

    public function test_social_xMentions(): void
    {
        $sq = $this->client();
        $sq->social->xMentions('test-id');
        $this->assertSame(['method' => 'GET', 'path' => '/social/accounts/test-id/x/mentions'], $this->calls[0]);
    }

    public function test_social_sendTypingIndicator(): void
    {
        $sq = $this->client();
        $sq->social->sendTypingIndicator('test-id');
        $this->assertSame(['method' => 'POST', 'path' => '/social/conversations/test-id/typing'], $this->calls[0]);
    }

    public function test_social_commentPrivateReply(): void
    {
        $sq = $this->client();
        $sq->social->commentPrivateReply('test-id', []);
        $this->assertSame(['method' => 'POST', 'path' => '/social/comments/test-id/private-reply'], $this->calls[0]);
    }

    public function test_social_getMessengerMenu(): void
    {
        $sq = $this->client();
        $sq->social->getMessengerMenu('test-id');
        $this->assertSame(['method' => 'GET', 'path' => '/social/accounts/test-id/messenger/menu'], $this->calls[0]);
    }

    public function test_social_setMessengerMenu(): void
    {
        $sq = $this->client();
        $sq->social->setMessengerMenu('test-id', []);
        $this->assertSame(['method' => 'PUT', 'path' => '/social/accounts/test-id/messenger/menu'], $this->calls[0]);
    }

    public function test_social_deleteMessengerMenu(): void
    {
        $sq = $this->client();
        $sq->social->deleteMessengerMenu('test-id');
        $this->assertSame(['method' => 'DELETE', 'path' => '/social/accounts/test-id/messenger/menu'], $this->calls[0]);
    }

    public function test_social_getIceBreakers(): void
    {
        $sq = $this->client();
        $sq->social->getIceBreakers('test-id');
        $this->assertSame(['method' => 'GET', 'path' => '/social/accounts/test-id/instagram/ice-breakers'], $this->calls[0]);
    }

    public function test_social_setIceBreakers(): void
    {
        $sq = $this->client();
        $sq->social->setIceBreakers('test-id', []);
        $this->assertSame(['method' => 'PUT', 'path' => '/social/accounts/test-id/instagram/ice-breakers'], $this->calls[0]);
    }

    public function test_social_deleteIceBreakers(): void
    {
        $sq = $this->client();
        $sq->social->deleteIceBreakers('test-id');
        $this->assertSame(['method' => 'DELETE', 'path' => '/social/accounts/test-id/instagram/ice-breakers'], $this->calls[0]);
    }

    public function test_social_facebookPageInsights(): void
    {
        $sq = $this->client();
        $sq->social->facebookPageInsights('test-id');
        $this->assertSame(['method' => 'GET', 'path' => '/social/accounts/test-id/facebook/page-insights'], $this->calls[0]);
    }

    public function test_social_instagramAudience(): void
    {
        $sq = $this->client();
        $sq->social->instagramAudience('test-id');
        $this->assertSame(['method' => 'GET', 'path' => '/social/accounts/test-id/instagram/audience'], $this->calls[0]);
    }

    public function test_social_connectOptions(): void
    {
        $sq = $this->client();
        $sq->social->connectOptions('test-id');
        $this->assertSame(['method' => 'GET', 'path' => '/social/accounts/test-id/connect-options'], $this->calls[0]);
    }

    public function test_social_connectSelect(): void
    {
        $sq = $this->client();
        $sq->social->connectSelect('test-id', []);
        $this->assertSame(['method' => 'POST', 'path' => '/social/accounts/test-id/connect-select'], $this->calls[0]);
    }

    public function test_urls_shorten(): void
    {
        $sq = $this->client();
        $sq->urls->shorten([]);
        $this->assertSame(['method' => 'POST', 'path' => '/urls/shorten'], $this->calls[0]);
    }

    public function test_urls_list(): void
    {
        $sq = $this->client();
        $sq->urls->list();
        $this->assertSame(['method' => 'GET', 'path' => '/urls'], $this->calls[0]);
    }

    public function test_urls_get(): void
    {
        $sq = $this->client();
        $sq->urls->get('test-id');
        $this->assertSame(['method' => 'GET', 'path' => '/urls/test-id'], $this->calls[0]);
    }

    public function test_urls_delete(): void
    {
        $sq = $this->client();
        $sq->urls->delete('test-id');
        $this->assertSame(['method' => 'DELETE', 'path' => '/urls/test-id'], $this->calls[0]);
    }

    public function test_urls_getStats(): void
    {
        $sq = $this->client();
        $sq->urls->getStats('test-id');
        $this->assertSame(['method' => 'GET', 'path' => '/urls/test-id/stats'], $this->calls[0]);
    }

    public function test_videos_listModels(): void
    {
        $sq = $this->client();
        $sq->videos->listModels();
        $this->assertSame(['method' => 'GET', 'path' => '/videos/models'], $this->calls[0]);
    }

    public function test_videos_generate(): void
    {
        $sq = $this->client();
        $sq->videos->generate([]);
        $this->assertSame(['method' => 'POST', 'path' => '/videos/generate'], $this->calls[0]);
    }

    public function test_videos_list(): void
    {
        $sq = $this->client();
        $sq->videos->list();
        $this->assertSame(['method' => 'GET', 'path' => '/videos'], $this->calls[0]);
    }

    public function test_videos_get(): void
    {
        $sq = $this->client();
        $sq->videos->get('test-id');
        $this->assertSame(['method' => 'GET', 'path' => '/videos/test-id'], $this->calls[0]);
    }

    public function test_videos_delete(): void
    {
        $sq = $this->client();
        $sq->videos->delete('test-id');
        $this->assertSame(['method' => 'DELETE', 'path' => '/videos/test-id'], $this->calls[0]);
    }

    public function test_videos_generateHook(): void
    {
        $sq = $this->client();
        $sq->videos->generateHook([]);
        $this->assertSame(['method' => 'POST', 'path' => '/videos/hook'], $this->calls[0]);
    }

    public function test_videos_suggestBroll(): void
    {
        $sq = $this->client();
        $sq->videos->suggestBroll([]);
        $this->assertSame(['method' => 'POST', 'path' => '/videos/broll-suggest'], $this->calls[0]);
    }

    public function test_videos_suggestEmphasis(): void
    {
        $sq = $this->client();
        $sq->videos->suggestEmphasis([]);
        $this->assertSame(['method' => 'POST', 'path' => '/videos/emphasis'], $this->calls[0]);
    }

    public function test_videos_generateViralThumbnail(): void
    {
        $sq = $this->client();
        $sq->videos->generateViralThumbnail([]);
        $this->assertSame(['method' => 'POST', 'path' => '/videos/viral-thumbnail'], $this->calls[0]);
    }

    public function test_webhooks_list(): void
    {
        $sq = $this->client();
        $sq->webhooks->list();
        $this->assertSame(['method' => 'GET', 'path' => '/webhooks'], $this->calls[0]);
    }

    public function test_webhooks_create(): void
    {
        $sq = $this->client();
        $sq->webhooks->create([]);
        $this->assertSame(['method' => 'POST', 'path' => '/webhooks'], $this->calls[0]);
    }

    public function test_webhooks_update(): void
    {
        $sq = $this->client();
        $sq->webhooks->update('test-id', []);
        $this->assertSame(['method' => 'PUT', 'path' => '/webhooks/test-id'], $this->calls[0]);
    }

    public function test_webhooks_delete(): void
    {
        $sq = $this->client();
        $sq->webhooks->delete('test-id');
        $this->assertSame(['method' => 'DELETE', 'path' => '/webhooks/test-id'], $this->calls[0]);
    }

    public function test_webhooks_listLogs(): void
    {
        $sq = $this->client();
        $sq->webhooks->listLogs();
        $this->assertSame(['method' => 'GET', 'path' => '/webhooks/logs'], $this->calls[0]);
    }

    public function test_webhooks_test(): void
    {
        $sq = $this->client();
        $sq->webhooks->test('test-id');
        $this->assertSame(['method' => 'POST', 'path' => '/webhooks/test-id/test'], $this->calls[0]);
    }

    public function test_workspaces_list(): void
    {
        $sq = $this->client();
        $sq->workspaces->list();
        $this->assertSame(['method' => 'GET', 'path' => '/workspaces'], $this->calls[0]);
    }

    public function test_workspaces_create(): void
    {
        $sq = $this->client();
        $sq->workspaces->create([]);
        $this->assertSame(['method' => 'POST', 'path' => '/workspaces'], $this->calls[0]);
    }

    public function test_workspaces_bulkAction(): void
    {
        $sq = $this->client();
        $sq->workspaces->bulkAction([]);
        $this->assertSame(['method' => 'POST', 'path' => '/workspaces/bulk'], $this->calls[0]);
    }

    public function test_workspaces_get(): void
    {
        $sq = $this->client();
        $sq->workspaces->get('test-id');
        $this->assertSame(['method' => 'GET', 'path' => '/workspaces/test-id'], $this->calls[0]);
    }

    public function test_workspaces_delete(): void
    {
        $sq = $this->client();
        $sq->workspaces->delete('test-id', []);
        $this->assertSame(['method' => 'DELETE', 'path' => '/workspaces/test-id'], $this->calls[0]);
    }

    public function test_workspaces_disableSaas(): void
    {
        $sq = $this->client();
        $sq->workspaces->disableSaas('test-id', []);
        $this->assertSame(['method' => 'POST', 'path' => '/workspaces/test-id/disable-saas'], $this->calls[0]);
    }

    public function test_workspaces_pause(): void
    {
        $sq = $this->client();
        $sq->workspaces->pause('test-id');
        $this->assertSame(['method' => 'POST', 'path' => '/workspaces/test-id/pause'], $this->calls[0]);
    }

    public function test_workspaces_resume(): void
    {
        $sq = $this->client();
        $sq->workspaces->resume('test-id');
        $this->assertSame(['method' => 'POST', 'path' => '/workspaces/test-id/resume'], $this->calls[0]);
    }

    public function test_workspaces_getSubscription(): void
    {
        $sq = $this->client();
        $sq->workspaces->getSubscription('test-id');
        $this->assertSame(['method' => 'GET', 'path' => '/workspaces/test-id/subscription'], $this->calls[0]);
    }

    public function test_workspaces_getWallet(): void
    {
        $sq = $this->client();
        $sq->workspaces->getWallet('test-id');
        $this->assertSame(['method' => 'GET', 'path' => '/workspaces/test-id/wallet'], $this->calls[0]);
    }

    public function test_workspaces_listSaasPlans(): void
    {
        $sq = $this->client();
        $sq->workspaces->listSaasPlans();
        $this->assertSame(['method' => 'GET', 'path' => '/saas/plans'], $this->calls[0]);
    }

    public function test_workspaces_getSaasPlan(): void
    {
        $sq = $this->client();
        $sq->workspaces->getSaasPlan('test-id');
        $this->assertSame(['method' => 'GET', 'path' => '/saas/plans/test-id'], $this->calls[0]);
    }
}
