<?php

/**
 * Generates tests/EndpointsGeneratedTest.php: one test per SDK method, calling
 * it against a mock transport and asserting the HTTP method + path it produces.
 * Proves the generated surface stays in lockstep with openapi.json.
 *
 * Run via `php scripts/generate-tests.php`.
 */

declare(strict_types=1);

require __DIR__ . '/model.php';

use function Smartlyq\Generator\buildModel;

/**
 * @param array{
 *     name: string, httpMethod: string, path: string,
 *     pathParams: list<array{arg: string, raw: string}>, hasBody: bool
 * } $m
 */
function emitTest(string $resourceKey, array $m): string
{
    $args = array_fill(0, count($m['pathParams']), "'test-id'");
    if ($m['hasBody']) {
        $args[] = '[]';
    }
    $expectedPath = preg_replace('/\{[^}]+\}/', 'test-id', $m['path']);

    return implode("\n", [
        '    public function test_' . $resourceKey . '_' . $m['name'] . '(): void',
        '    {',
        '        $sq = $this->client();',
        '        $sq->' . $resourceKey . '->' . $m['name'] . '(' . implode(', ', $args) . ');',
        "        \$this->assertSame(['method' => '" . $m['httpMethod'] . "', 'path' => '" . $expectedPath . "'], \$this->calls[0]);",
        '    }',
    ]);
}

$root = dirname(__DIR__);
$resources = buildModel($root . '/openapi.json');

$tests = [];
foreach ($resources as $r) {
    foreach ($r['methods'] as $m) {
        $tests[] = emitTest($r['key'], $m);
    }
}

$content = implode("\n", [
    '<?php',
    '',
    '// This file is auto-generated by scripts/generate-tests.php. Do not edit by hand.',
    '',
    'declare(strict_types=1);',
    '',
    'use PHPUnit\\Framework\\TestCase;',
    'use Smartlyq\\SmartlyQ;',
    '',
    'final class EndpointsGeneratedTest extends TestCase',
    '{',
    '    /** @var list<array{method: string, path: string}> */',
    '    private array $calls = [];',
    '',
    '    private function client(): SmartlyQ',
    '    {',
    '        $this->calls = [];',
    '        $transport = function (string $method, string $url, array $headers, ?string $body, float $timeout): array {',
    '            $path = (string) parse_url($url, PHP_URL_PATH);',
    "            if (str_starts_with(\$path, '/v1')) {",
    '                $path = substr($path, 3);',
    '            }',
    "            \$this->calls[] = ['method' => \$method, 'path' => \$path];",
    '',
    '            return [',
    "                'status' => 200,",
    "                'headers' => ['content-type' => 'application/json'],",
    '                \'body\' => \'{"success":true,"data":{}}\',',
    '            ];',
    '        };',
    '',
    "        return new SmartlyQ('sqk_test_xxxxxxxxxxxx', ['transport' => \$transport, 'max_retries' => 0]);",
    '    }',
    '',
    implode("\n\n", $tests),
    '}',
    '',
]);

file_put_contents($root . '/tests/EndpointsGeneratedTest.php', $content);
echo 'Generated tests/EndpointsGeneratedTest.php: ' . count($tests) . " endpoint tests.\n";
