<?php

/**
 * Generates the SDK surface from openapi.json:
 *   - src/Resources/{Tag}Resource.php - one class per API tag
 *   - src/SmartlyQ.php                - the facade wiring every resource
 *
 * Run via `php scripts/generate-client.php`.
 */

declare(strict_types=1);

require __DIR__ . '/model.php';

use function Smartlyq\Generator\buildModel;
use function Smartlyq\Generator\snakeToCamel;

const GENERATED_NOTICE = '// This file is auto-generated by scripts/generate-client.php. Do not edit by hand.';

/** @param array{path: string, pathParams: list<array{arg: string, raw: string}>} $m */
function pathExpression(array $m): string
{
    if ($m['pathParams'] === []) {
        return var_export($m['path'], true);
    }

    $parts = preg_split('/(\{[^}]+\})/', $m['path'], -1, PREG_SPLIT_DELIM_CAPTURE | PREG_SPLIT_NO_EMPTY);
    $pieces = [];
    foreach ($parts as $part) {
        if (preg_match('/^\{([^}]+)\}$/', $part, $match)) {
            $pieces[] = 'rawurlencode($' . snakeToCamel($match[1]) . ')';
        } else {
            $pieces[] = var_export($part, true);
        }
    }

    return implode(' . ', $pieces);
}

/**
 * @param array{
 *     name: string, httpMethod: string, path: string, summary: string,
 *     pathParams: list<array{arg: string, raw: string}>,
 *     hasBody: bool, bodyRequired: bool, hasQuery: bool
 * } $m
 */
function emitMethod(array $m): string
{
    $args = [];
    foreach ($m['pathParams'] as $p) {
        $args[] = 'string $' . $p['arg'];
    }
    if ($m['hasBody']) {
        $args[] = $m['bodyRequired'] ? 'array $body' : 'array $body = []';
    }
    if ($m['hasQuery']) {
        $args[] = 'array $query = []';
    }
    $args[] = 'array $options = []';

    $req = [];
    if ($m['hasBody']) {
        $req[] = "'body' => \$body";
    }
    if ($m['hasQuery']) {
        $req[] = "'query' => \$query";
    }
    $req[] = "'options' => \$options";

    $summary = str_replace('*/', '*\/', $m['summary']);

    return implode("\n", [
        '    /**',
        '     * ' . $summary,
        '     *',
        '     * ' . $m['httpMethod'] . ' ' . $m['path'],
        '     */',
        '    public function ' . $m['name'] . '(' . implode(', ', $args) . '): array',
        '    {',
        "        return \$this->client->request('" . $m['httpMethod'] . "', " . pathExpression($m) . ', [',
        '            ' . implode(",\n            ", $req) . ',',
        '        ]);',
        '    }',
    ]);
}

$root = dirname(__DIR__);
$resources = buildModel($root . '/openapi.json');

// Remove stale resource classes so renamed/removed tags do not linger.
foreach (glob($root . '/src/Resources/*.php') ?: [] as $stale) {
    unlink($stale);
}

foreach ($resources as $r) {
    $methods = array_map('emitMethod', $r['methods']);
    $content = implode("\n", [
        '<?php',
        '',
        GENERATED_NOTICE,
        '',
        'declare(strict_types=1);',
        '',
        'namespace Smartlyq\\Resources;',
        '',
        'use Smartlyq\\CoreClient;',
        '',
        '/** ' . $r['tag'] . ' endpoints. */',
        'class ' . $r['className'],
        '{',
        '    public function __construct(private readonly CoreClient $client)',
        '    {',
        '    }',
        '',
        implode("\n\n", $methods),
        '}',
        '',
    ]);
    file_put_contents($root . '/src/Resources/' . $r['className'] . '.php', $content);
}

// Facade with one typed readonly property per resource.
$uses = [];
$properties = [];
$assignments = [];
foreach ($resources as $r) {
    $uses[] = 'use Smartlyq\\Resources\\' . $r['className'] . ';';
    $properties[] = '    /** ' . $r['tag'] . ' endpoints. */';
    $properties[] = '    public readonly ' . $r['className'] . ' $' . $r['key'] . ';';
    $properties[] = '';
    $assignments[] = '        $this->' . $r['key'] . ' = new ' . $r['className'] . '($this->client);';
}
array_pop($properties);

$facade = implode("\n", [
    '<?php',
    '',
    GENERATED_NOTICE,
    '',
    'declare(strict_types=1);',
    '',
    'namespace Smartlyq;',
    '',
    implode("\n", $uses),
    '',
    '/**',
    ' * SmartlyQ API client.',
    ' *',
    ' *     $sq = new \\Smartlyq\\SmartlyQ(\'sqk_live_xxxxxxxxxxxx\');',
    ' *     $post = $sq->social->createPost([',
    ' *         \'text\' => \'Hello from the SmartlyQ SDK!\',',
    ' *         \'account_ids\' => [\'acc_123\'],',
    ' *     ]);',
    ' *',
    ' * The API key falls back to the SMARTLYQ_API_KEY environment variable.',
    ' * Options: base_url, timeout (seconds), max_retries, default_headers, transport.',
    ' */',
    'class SmartlyQ',
    '{',
    '    public readonly CoreClient $client;',
    '',
    implode("\n", $properties),
    '',
    '    /** @param array<string, mixed> $options See CoreClient for supported options. */',
    '    public function __construct(?string $apiKey = null, array $options = [])',
    '    {',
    '        $this->client = new CoreClient($apiKey, $options);',
    implode("\n", $assignments),
    '    }',
    '}',
    '',
]);
file_put_contents($root . '/src/SmartlyQ.php', $facade);

$opCount = array_sum(array_map(static fn (array $r): int => count($r['methods']), $resources));
echo 'Generated src/Resources/ and src/SmartlyQ.php: ' . count($resources) . ' resources, ' . $opCount . " methods.\n";
