<?php

// This file is auto-generated by scripts/generate-client.php. Do not edit by hand.

declare(strict_types=1);

namespace Smartlyq;

use Smartlyq\Resources\AccountResource;
use Smartlyq\Resources\CaptainResource;
use Smartlyq\Resources\AnalyticsResource;
use Smartlyq\Resources\ArticlesResource;
use Smartlyq\Resources\AudioResource;
use Smartlyq\Resources\AutomationsResource;
use Smartlyq\Resources\ChatbotsResource;
use Smartlyq\Resources\CommentsResource;
use Smartlyq\Resources\ContentResource;
use Smartlyq\Resources\CRMResource;
use Smartlyq\Resources\ContactsResource;
use Smartlyq\Resources\CustomFieldsResource;
use Smartlyq\Resources\OpportunitiesResource;
use Smartlyq\Resources\MessagesResource;
use Smartlyq\Resources\ImagesResource;
use Smartlyq\Resources\JobsResource;
use Smartlyq\Resources\LogsResource;
use Smartlyq\Resources\MediaResource;
use Smartlyq\Resources\PresentationsResource;
use Smartlyq\Resources\ProfilesResource;
use Smartlyq\Resources\ReviewsResource;
use Smartlyq\Resources\SeoResource;
use Smartlyq\Resources\ShortsResource;
use Smartlyq\Resources\SocialResource;
use Smartlyq\Resources\UrlsResource;
use Smartlyq\Resources\VideosResource;
use Smartlyq\Resources\WebhooksResource;
use Smartlyq\Resources\WhatsAppResource;
use Smartlyq\Resources\WorkspacesResource;

/**
 * SmartlyQ API client.
 *
 *     $sq = new \Smartlyq\SmartlyQ('sqk_live_xxxxxxxxxxxx');
 *     $post = $sq->social->createPost([
 *         'text' => 'Hello from the SmartlyQ SDK!',
 *         'account_ids' => ['acc_123'],
 *     ]);
 *
 * The API key falls back to the SMARTLYQ_API_KEY environment variable.
 * Options: base_url, timeout (seconds), max_retries, default_headers, transport.
 */
class SmartlyQ
{
    public readonly CoreClient $client;

    /** Account endpoints. */
    public readonly AccountResource $account;

    /** AI Captain endpoints. */
    public readonly CaptainResource $captain;

    /** Analytics endpoints. */
    public readonly AnalyticsResource $analytics;

    /** Articles endpoints. */
    public readonly ArticlesResource $articles;

    /** Audio endpoints. */
    public readonly AudioResource $audio;

    /** Automations endpoints. */
    public readonly AutomationsResource $automations;

    /** Chatbot endpoints. */
    public readonly ChatbotsResource $chatbots;

    /** Comments endpoints. */
    public readonly CommentsResource $comments;

    /** Content endpoints. */
    public readonly ContentResource $content;

    /** CRM endpoints. */
    public readonly CRMResource $cRM;

    /** CRM Contacts endpoints. */
    public readonly ContactsResource $contacts;

    /** CRM Custom Fields endpoints. */
    public readonly CustomFieldsResource $customFields;

    /** CRM Opportunities endpoints. */
    public readonly OpportunitiesResource $opportunities;

    /** Direct Messages endpoints. */
    public readonly MessagesResource $messages;

    /** Images endpoints. */
    public readonly ImagesResource $images;

    /** Jobs endpoints. */
    public readonly JobsResource $jobs;

    /** Logs endpoints. */
    public readonly LogsResource $logs;

    /** Media endpoints. */
    public readonly MediaResource $media;

    /** Presentations endpoints. */
    public readonly PresentationsResource $presentations;

    /** Profiles endpoints. */
    public readonly ProfilesResource $profiles;

    /** Reviews endpoints. */
    public readonly ReviewsResource $reviews;

    /** SEO endpoints. */
    public readonly SeoResource $seo;

    /** Shorts endpoints. */
    public readonly ShortsResource $shorts;

    /** Social endpoints. */
    public readonly SocialResource $social;

    /** URLs endpoints. */
    public readonly UrlsResource $urls;

    /** Videos endpoints. */
    public readonly VideosResource $videos;

    /** Webhooks endpoints. */
    public readonly WebhooksResource $webhooks;

    /** WhatsApp endpoints. */
    public readonly WhatsAppResource $whatsApp;

    /** Workspaces endpoints. */
    public readonly WorkspacesResource $workspaces;

    /** @param array<string, mixed> $options See CoreClient for supported options. */
    public function __construct(?string $apiKey = null, array $options = [])
    {
        $this->client = new CoreClient($apiKey, $options);
        $this->account = new AccountResource($this->client);
        $this->captain = new CaptainResource($this->client);
        $this->analytics = new AnalyticsResource($this->client);
        $this->articles = new ArticlesResource($this->client);
        $this->audio = new AudioResource($this->client);
        $this->automations = new AutomationsResource($this->client);
        $this->chatbots = new ChatbotsResource($this->client);
        $this->comments = new CommentsResource($this->client);
        $this->content = new ContentResource($this->client);
        $this->cRM = new CRMResource($this->client);
        $this->contacts = new ContactsResource($this->client);
        $this->customFields = new CustomFieldsResource($this->client);
        $this->opportunities = new OpportunitiesResource($this->client);
        $this->messages = new MessagesResource($this->client);
        $this->images = new ImagesResource($this->client);
        $this->jobs = new JobsResource($this->client);
        $this->logs = new LogsResource($this->client);
        $this->media = new MediaResource($this->client);
        $this->presentations = new PresentationsResource($this->client);
        $this->profiles = new ProfilesResource($this->client);
        $this->reviews = new ReviewsResource($this->client);
        $this->seo = new SeoResource($this->client);
        $this->shorts = new ShortsResource($this->client);
        $this->social = new SocialResource($this->client);
        $this->urls = new UrlsResource($this->client);
        $this->videos = new VideosResource($this->client);
        $this->webhooks = new WebhooksResource($this->client);
        $this->whatsApp = new WhatsAppResource($this->client);
        $this->workspaces = new WorkspacesResource($this->client);
    }
}
